### PR TITLE
Bump Zygote to 0.4.20

### PR DESCRIPTION
**Pull request by aminya**

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
Let's drop the patch maybe

**Comment by aminya** [comment]
@dhairyagandhi96 is there a reason to use `Manifest.toml` on master? This breaks backward compatibility for older Julia versions, and it is highly recommended against.

**Comment by dhairyagandhi96** [comment]
There's some discussion here https://github.com/FluxML/Zygote.jl/pull/629#issuecomment-624007699

**Comment by dhairyagandhi96** [comment]
Can we fix the conflicts? I'd love to merge this

**Comment by aminya** [comment]
Remove the Manifest from the master. Then you can merge this.
https://github.com/FluxML/Flux.jl/issues/1164

**Comment by CarloLucibello** [comment]
not needed anymore

**Pull request closed without merging**
