### PR TITLE
Fix RNN tests on GPU

### PR DESCRIPTION
**Pull request by jeremiedb**
Fix for RNN on CUDA, as discussed in #1367 .

### CODE REVIEW

**Comment by jeremiedb** [comment]
@DhairyaLGandhi Is it good for review?

**Comment by DhairyaLGandhi** [comment]
I'm slightly confused by this, if the tests were passing all this while, then why did we not see the `unexpected pass ...` , and if they were indeed working we wouldn't have marked them broken.

bors try

**Comment by jeremiedb** [comment]
They were not previously passing given the `m̄[].cell[].Wi` was to be changed to `m̄[].cell.Wi`.

**Comment by DhairyaLGandhi** [comment]
Ah cool, sorry I missed that

**Comment by DhairyaLGandhi** [comment]
bors try-

**Pull request merged**
