### PR TITLE
Added vcat for multiple TrackedVectors

### PR DESCRIPTION
**Pull request by GenaBitu**
Note: the previous line to this addition must be left as is to prevent ambiguity when concatenating 2 vectors

### CODE REVIEW

**Comment by GenaBitu** [comment]
back not yet working, do not merge, will try to fix it...

**Comment by GenaBitu** [comment]
Ok, back should now work as well

**Comment by MikeInnes** [comment]
Cool, thanks. Can you add a gradient check for this as well?

Would be great to have a more general `cat` as well.

**Comment by GenaBitu** [comment]
Do you mean this check?

**Comment by MikeInnes** [comment]
Thanks a lot for the patch!

**Pull request merged**
