### PR TITLE
add Flux.skip()

### PR DESCRIPTION
**Pull request by Moelf**
per #821

### PR Checklist

- [x] Tests are added
- [ ] Entry in NEWS.md
- [x] Documentation, if applicable
- [ ] Final review from `@MikeInnes` or `@dhairyagandhi96` (for API changes).

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Can we add tests in here please?

**Comment by DhairyaLGandhi** [comment]
bump

**Comment by Moelf** [comment]
added

**Comment by Moelf** [comment]
@DhairyaLGandhi bump

**Comment by DhairyaLGandhi** [comment]
Thanks for the bump, this is really close. One nit, could we have the test skip for a particular value of `i`? That way it's easier to determine what the skip is intended for

**Comment by DhairyaLGandhi** [comment]
Nice, thanks!

bors r+

**Pull request merged**
