### PR TITLE
Implement Gated Recurrent Unit

### LINKED ISSUE #90: GRU recurrent cell
Along with other recurrent layers we're missing. See the [current implementations](https://github.com/FluxML/Flux.jl/blob/master/src/layers/recurrent.jl) of LSTM and RNN for reference.

### PR DESCRIPTION
**Pull request by baggepinnen**
Fixes #90  :)
Tests are coming

### CODE REVIEW

**Comment by baggepinnen** [comment]
Actually, I can not find tests on other recurrent layers. Any suggestions on reasonable ways of testing these?

**Comment by MikeInnes** [comment]
For a test, how about learning to predict a trivial sequence (perhaps alternating `[1, 0]`, `[0, 1]`)? All RNNs should be capable of that, I think.

**Comment by baggepinnen** [comment]
I had an idea along those lines initially, but was hesitating to implement it since I thought the time required to test the package would become very large if several layers had tests that required a train loop..

**Comment by MikeInnes** [comment]
If it's simple enough it should train pretty quickly. We already do this with the optimisers as well.

**Comment by MikeInnes** [comment]
Merging this for now and we'll figure out the tests. Thanks @baggepinnen!

**Pull request merged**
