### PR TITLE
added sigmoid function

### PR DESCRIPTION
**Pull request by tk3369**
I wasn't able to complete the tutorial in REPL since `σ` wasn't defined.  This PR updates the code sample with the sigmoid function.

### CODE REVIEW

**Comment by johnnychen94** [comment]
check [NNLib](https://github.com/FluxML/NNlib.jl/blob/91fe82da545f5faa07be48f8afd9b97c15929c71/src/activation.jl#L7)

**Comment by MikeInnes** [comment]
This should definitely be fixed so that it can be run without changes. Adding `using Flux` to this would solve it, since that exports `σ`.

**Comment by tk3369** [comment]
Closing this PR. Just adding `using Flux` sounds like a great idea.

**Comment by MikeInnes** [comment]
Someone still has to add that though :) Are you up for making another PR, or updating this one?

**Pull request closed without merging**
