### PR TITLE
add Julia ecosystem doc section

### PR DESCRIPTION
**Pull request by CarloLucibello**
Partially fixing #251,  related to the discussion in #1051 .

Not exactly a poem that I wrote here, maybe someone could suggest a better rephrasing. 
Suggestion for additional packages to add to the list also welcome

### CODE REVIEW

**Comment by johnnychen94** [comment]
Just kidding, I feel like I'm threatened to update Augmentor's documentation ASAP

**Comment by CarloLucibello** [comment]
> Just kidding, I feel like I'm threatened to update Augmentor's documentation ASAP

ahah, actually Augmentor looks pretty cool

**Pull request merged**
