### PR TITLE
Allow CuArrays v2.x

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
bors try

**Comment by dhairyagandhi96** [comment]
Could you also bump the version in the Manifest please? Thanks @ararslan!

**Comment by ararslan** [comment]
Done!

**Comment by ararslan** [comment]
Hm, I'm not sure what's going on with the Travis failure but it does look related. I guess it's expecting a CUDA installation, which is why it worked on the GPU-enabled Gitlab CI.

**Comment by ararslan** [comment]
The amazing @maleadt found that the source of the issue is with CUDAdrv. He'll be addressing that (with tests to catch it) upstream soon.

**Comment by ararslan** [comment]
Ah, looks like this will need https://github.com/JuliaGPU/CuArrays.jl/pull/650 too.

**Comment by maleadt** [comment]
https://github.com/JuliaRegistries/General/pull/11588. I think this will also need https://github.com/FluxML/Flux.jl/pull/1050 though.

**Comment by CarloLucibello** [comment]
@maleadt we should drop cuarrays 1.6 support if #1050 gets in, right?

**Comment by dhairyagandhi96** [comment]
Merged #1050 here, could use a manifest bump

**Comment by maleadt** [comment]
> @maleadt we should drop cuarrays 1.6 support if #1050 gets in, right?

Correct.

**Comment by dhairyagandhi96** [comment]
Is it limited to 1.6 or would we also drop 1.7 support here?

**Comment by maleadt** [comment]
> Is it limited to 1.6 or would we also drop 1.7 support here?

Sorry, you also need to drop 1.7. The change is only in 2.0.

**Comment by maleadt** [comment]
bors try

**Comment by dhairyagandhi96** [comment]
Thanks guys!

**Comment by jgreener64** [comment]
Patch release would be really useful.

**Pull request merged**
