### PR TITLE
RFC: Replace Requires with direct CuArrays dependency.

### PR DESCRIPTION
**Pull request by maleadt**
Instead of depending indirectly on CuArrays through Requires, this PR adds a proper dependency on the package, and uses CUDAapi to figure out if we can actually load CuArrays. Advantages: actual version compatibility, which should improve the usability of the package. Disadvantages: some additional packages are installed on every system, even without a GPU. Proper conditional dependencies would be a better solution, but for now this seems like an improvement.

Requires a tag of CUDAnative: https://github.com/JuliaRegistries/General/pull/2978
Ref https://discourse.julialang.org/t/cuarrays-cudanative-psa-simplified-package-loading/27897

### CODE REVIEW

**Comment by MikeInnes** [comment]
Awesome, thanks!

**Comment by janEbert** [comment]
Hey, would it be possible to also add a function which can disable the loading of CuArrays?
With #848 and other possible errors, it would be nice to selectively turn off GPU usage which would otherwise require modifying `JULIA_LOAD_PATH` or writing a wrapper around `Flux.gpu`.

**Comment by MikeInnes** [comment]
Couldn't you just not call `Flux.gpu`?

**Comment by janEbert** [comment]
But then if I wanted to use the GPU I'd have to change every usage.

**Comment by maleadt** [comment]
I'd even argue that calling `gpu` when the GPU stack is not functional should error, or at least warn.

**Comment by janEbert** [comment]
I was gonna say that that is what I like about the function – that you can just call it always because it does the right thing but I guess then Flux could just always call it internally. I see your points. :)

**Comment by MikeInnes** [comment]
You can just define something like
```julia
enable_gpu = true
foo(x) = enable_gpu ? gpu(x) : x

m = Chain(...) |> foo
```

**Comment by xukai92** [comment]
When is the check of CuArrys done? I have been having issue on `Flux.gpu` since this PR is merged. While my machine does have CUDA and CuArrays, the `Flux.gpu` sometimes just doesn't work, usually after I do `] update` and everything got compiled or built again.

My `Flux.gpu` is not working ATM. Any information I can provide to help diagnosis this?

**Comment by maleadt** [comment]
There is one corner case I have not found a workaround, and you might be running into this: if at some point your GPU environment was broken, and CuArrays failed to import (or CUDAapi decided you didn't have a GPU/CUDA), Flux will be precompiled "without" GPU support, since those checks happen in global scope when the package is precompiled.

To fix this, we'd need to consult CUDAapi from init, but also be able to somehow declare a precompile dependency on CuArrays even if it failed to import (in order to trigger recompilation of Flux when CuArrays gets updated). I haven't found a way to do that.

Workaround; delete `~/.julia/compiled`.

**Comment by xukai92** [comment]
Can I ask Julia to re-precompile Flux somehow to achive the same thing?

**Comment by xukai92** [comment]
I mean by a command or function.

**Comment by maleadt** [comment]
```
julia> Base.compilecache(Base.PkgId("Flux"))
```

**Comment by xukai92** [comment]
Cool. Thanks!

**Comment by xukai92** [comment]
> There is one corner case I have not found a workaround, and you might be running into this: if at some point your GPU environment was broken, and CuArrays failed to import (or CUDAapi decided you didn't have a GPU/CUDA), Flux will be precompiled "without" GPU support, since those checks happen in global scope when the package is precompiled.

I think my case is exactly this. In my uni, all the server uses the same afs to store files. I have used Flux on a sever with only CPUs and then started to use one with GPUs. And it doesn't seem to be re-precompiled in this case as the filesytem is shared.

**Comment by maleadt** [comment]
I guess we could do the CUDAapi check during `__init__`, and that would cover most (including your) cases. Let me have a look.

**Comment by xukai92** [comment]
Also how should it work with environment? I think logically Flux should not load GPU if there is no CuArrays in the activated environment, even the machine has GPUs, right?

**Comment by maleadt** [comment]
Flux now depends on CuArrays, so it's always in the environment.

**Comment by xukai92** [comment]
Oh yes you are right.

**Pull request merged**
