### PR TITLE
Minor RNNCell docs fix

### PR DESCRIPTION
**Pull request by JobJob**
This is what you meant right? It matches the preceding example.

Really liking the look of this new version btw!

### CODE REVIEW

**Comment by JobJob** [comment]
Oh actually, that gives a `invalid redefinition of constant rnn` - since the rnn function is defined above.

Maybe it should be `rnn2` or `rnn_cell` or `rnncell`? or change the bottom function to `m`? Decisions are the worst.

**Comment by MikeInnes** [comment]
Yeah, that was why I changed it from `rnn`. I'd be fine with `rnn2`, or just changing the function call to `m`.

**Comment by JobJob** [comment]
I chose rnn2 - to be most similar to the prev example, squash and merge? 
If you need me to rebase and/or squash myself, lemme know.

**Comment by MikeInnes** [comment]
Thanks!

**Pull request merged**
