### PR TITLE
fix: CUDA package optional for FluxMPIExt

### PR DESCRIPTION
**Pull request by askorupka**
Hotfix for https://github.com/FluxML/Flux.jl/pull/2464 the issue reported by @kishore-nori (https://github.com/FluxML/Flux.jl/pull/2464#issuecomment-2375891808)

### CODE REVIEW

**Review by CarloLucibello — APPROVED** [review]

**Comment by kishore-nori** [comment]
Thank you very much @askorupka

**Comment by askorupka** [comment]
You're welcome and thanks for reporting the bug @kishore-nori !

**Comment by kishore-nori** [comment]
Hi @askorupka, sorry for bugging you again on this. I have come across the same precompilation error again when `CUDA.jl` is in the package environment. And I add `MPI.jl` and `Flux.jl`. (The error doesn't occur when `CUDA.jl` is not in the package environment)

```julia
ERROR: LoadError: ArgumentError: Package FluxMPIExt does not have CUDA in its dependencies:
- You may have a partially installed environment. Try `Pkg.instantiate()`
  to ensure all packages in the environment are installed.
- Or, if you have FluxMPIExt checked out for development and have
  added CUDA as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with FluxMPIExt 
```

can you check if this occurs for you as well? I would suggest clearing the `Flux.jl` compilations from `.julia` folder, to reproduce the error.

**Comment by ToucheSir** [comment]
I would recommend continuing discussion on #2490 since open issues are more discoverable.

**Pull request merged**
