### PR TITLE
Support copy(::TrackedArray)

### PR DESCRIPTION
**Pull request by johnnychen94**
1. fix issue https://github.com/FluxML/Flux.jl/issues/416
2. change test code to pass the test: some broken tests are not broken now...

### CODE REVIEW

**Comment by MikeInnes** [comment]
Thanks, but can you just add the `copy` method directly to fix this. Otherwise this will cause `copy` to silently drop gradients.

I think the `@test_throws` is right; we're testing that we get an ambiguity as opposed to a dropped gradient etc.

**Comment by johnnychen94** [comment]
You mean codes like these right?
```julia
Base.copy(x::TrackedReal) = copy(data(x))
Base.copy(x::TrackedArray) = copy(data(x))
```

I use this `convert` code because the behavior of  `convert(::Type{T}, x::TrackedReal{S})` is clear -- the tracked gradients can be dropped.

I'm not clear about `copy` though, should we keep the gradients in `copy(::TrackedArray)`?

**Comment by MikeInnes** [comment]
You can just write `Base.copy(x::TrackedReal) = x`, since we treat tracked objects as immutable anyway.

The problem with dropping gradients is that it's implicit, and (for example) in this case would have led `copy` to silently drop gradients as well; this kind of thing can easily lead to confusing bugs in code.

**Comment by johnnychen94** [comment]
Alright, done as you said. 

Thanks for your patience to explain this

**Comment by MikeInnes** [comment]
No problem, thank you for putting it together!

**Pull request merged**
