### PR TITLE
Fix Glorot initialization, add He initialization

### LINKED ISSUE #442: Glorot initialization not correctly implemented
I think the Glorot initializations are not correctly implemented.

https://github.com/FluxML/Flux.jl/blob/cb773e54c0dbb5337bbd3318acb3ae79c1979b01/src/utils.jl#L4-L5

e.g. `glorot_uniform` should sample from a uniform distribution [-limit, limit] where limit = sqrt(6 / (fan_in + fan_out))

For a dense layer the `sum(dims)` will give the correct result for (fan_in + fan_out), but I think this does not hold in the case of convolutions anymore. I think here it should be `*(dims[1:end-1]...) + dims[end]`

### PR DESCRIPTION
**Pull request by Sleort**
Should fix #442 .
Adds He weight initialization as a bonus :-)

### CODE REVIEW

**Comment by MikeInnes** [comment]
Why the close, is this superceded by something?

At any rate, it'd be best to split this into two PRs.

**Comment by MikeInnes** [comment]
Just saw #937.

**Comment by Sleort** [comment]
> Just saw #937.

Sorry about that. I was too trigger-happy with the first commit, and discovered I needed to fix a couple of things before resubmitting...

(I'm kind in a learning phase regarding git / Github, so please let me know if this wasn't the proper way of doing it... )

**Comment by MikeInnes** [comment]
Yes, you can change the PR so there's generally no need to open a new one for the same thing. Adding new commits and pushing them is the simplest way; if you want to go a bit more advanced and clean up history the most useful option to learn about is `git rebase -i`.

**Comment by Sleort** [comment]
Thanks for the tip!

**Pull request closed without merging**
