### PR TITLE
Add a variant of Adam called "PAdam"

### PR DESCRIPTION
**Pull request by 4SAnalyticsnModelling**
Add a variant of Adam optimizer called "partially adaptive momentum estimation method (PAdam)"

### CODE REVIEW

**Comment by CarloLucibello** [comment]
why did you open so many PRs?

**Comment by mcabbott** [comment]
When I looked the most meat was in https://github.com/FluxML/Flux.jl/pull/2276 . The others should be commits on that branch, not indep. PRs.

**Comment by 4SAnalyticsnModelling** [comment]
@CarloLucibello, I apologize for creating confusion with so many PRs. As @mcabbott mentioned, they are all related PRs. While #2276 has most of the meet, the other commits are also required to make the changes work. I wasn't sure how to include all of those changes in one PR, that's why I went to create so many of them.

**Comment by mcabbott** [comment]
Somehow you need to push more commits to the same branch, which will update the PR. It's generally easiest to do things on your computer, rather than on github's website... I'm not sure I know how to move commits using the website, but this is called `git cherry-pick` locally. These things are confusing at first but soon become second nature. 

I like this guide but not sure it's the ideal reference:

https://kshyatt.github.io/post/firstjuliapr/

**Comment by 4SAnalyticsnModelling** [comment]
Thanks @mcabbott! I'll follow the article and give it a try to see if I can make all the related commits to one branch.

**Pull request closed without merging**
