### PR TITLE
Fix issue #323

### PR DESCRIPTION
**Pull request by johnnychen94**
add support for ≈ operation for types `TrackedArray` and `TrackedReal`

### CODE REVIEW

**Comment by MikeInnes** [comment]
Thanks! Can you add a quick test for this?

**Comment by johnnychen94** [comment]
Done as you said. Also fixed an existing bug.

```julia
param([2]).^2 == [4.0]
ERROR: MethodError: ==(::TrackedArray{…,Array{Float64,1}}, ::Array{Float64,1}) is ambiguous. Candidates:
==(x::TrackedArray, y) in Main.Flux.Tracker at /Users/jc/.julia/dev/Flux/src/tracker/array.jl:63
==(A::AbstractArray, B::AbstractArray) in Base at abstractarray.jl:1686
Possible fix, define
==(::TrackedArray, ::AbstractArray)
```

**Comment by MikeInnes** [comment]
Looks good, thanks a lot @johnnychen94.

Just as a tip for future PRs – It's better if your title is a bit more descriptive, rather than just referencing another issue number (which I have not memorised :smile:). If you put issue references in the body of the PR they'll also get turned into links, which is handy. "Add support for ≈" would have been an ideal title for this.

**Comment by johnnychen94** [comment]
I'm still in the progress of learning how to use Github as an expert =.= Thanks for your feedback I'll keep this in mind.

**Pull request merged**
