### PR TITLE
Fix Glorot initialization, add He initialization

### LINKED ISSUE #442: Glorot initialization not correctly implemented
I think the Glorot initializations are not correctly implemented.

https://github.com/FluxML/Flux.jl/blob/cb773e54c0dbb5337bbd3318acb3ae79c1979b01/src/utils.jl#L4-L5

e.g. `glorot_uniform` should sample from a uniform distribution [-limit, limit] where limit = sqrt(6 / (fan_in + fan_out))

For a dense layer the `sum(dims)` will give the correct result for (fan_in + fan_out), but I think this does not hold in the case of convolutions anymore. I think here it should be `*(dims[1:end-1]...) + dims[end]`

### PR DESCRIPTION
**Pull request by Sleort**
Should fix #442 .
Adds He weight initialization as a bonus :-)

### CODE REVIEW

**Comment by MikeInnes** [comment]
Best to split this into two PRs to make it easier to review and merge.

**Comment by Sleort** [comment]
I couldn't figure out how to split the PR into two, so I deleted the He initialization stuff (for now). 

(And sorry for the mess. I'm not yet completely familiar/comfortable with how Git(hub) works...)

**Comment by MikeInnes** [comment]
No worries. Splitting the commit is possible but it's usually easier just to delete code and/or copy-paste it somewhere else for the `he` PR, so that's the right thing to do.

**Comment by Sleort** [comment]
Anything else I should do to get this PR reviewed / merged?

**Comment by MikeInnes** [comment]
I'm a bit uncomfortable with the heuristic this uses, but at least it has good precedent in other libraries. We can always redesign in future if needed.

Thanks @Sleort!

bors r+

**Comment by Sleort** [comment]
> I'm a bit uncomfortable with the heuristic this uses, but at least it has good precedent in other libraries. We can always redesign in future if needed.

I agree (see the discussion at #442). A more "proper" way of treating this would, however, require breaking changes, since we would have to dispatch on layer type in addition to dimensionality. Actually, ideally we should maybe make the initialization depend on the activation function as well, such that the "right" initialization could be automatically selected (Glorot for `tanh`, He for `relu`, etc.)...?

**Comment by MikeInnes** [comment]
We don't generally consider changing a layer's default initialisation to be breaking, so we could make the defaults smarter at any time, even if it isn't exposed as an API. A more general user-accessible initialisation API would be nice to have though.

**Pull request merged**
