### PR TITLE
fixed docstrings in the module

### PR DESCRIPTION
**Pull request by Dsantra92**
the docstrings in the module for functions onhot and onecold  proposed a function with some examples that returns 0 or 1 instead of boolean .

### CODE REVIEW

**Comment by CarloLucibello** [comment]
docstring seems correct though
```julia
julia> onehot(:b, [:a, :b, :c])
3-element Flux.OneHotVector:
 0
 1
 0
```

**Comment by Dsantra92** [comment]
I thought it should return true and false instead of 0 and 1s.

**Comment by bhvieira** [comment]
Docs are conflicting on this right now. Going by `src/data/onehot.md`, you are right. Ping @janEbert

@CarloLucibello the code for `OneHotVector` implies it returns booleans, and it is true on my Flux (v0.10.2).

**Comment by janEbert** [comment]
Hey, thanks for the ping! You are absolutely right, the docstrings are wrong, but in the inverted way, as @bhvieira said.
They mention the function would return a vector with `true` at the `l`-th position which is incorrect. I actually find I rewrote that docstring very badly; due to calling it the `l`-th position and the first argument also being named `l`, it is very confusing. It should rather be written with the `k`-th position, for example. The docstring in general does not really explain what the function does to a newbie so it could use a better, newer one.

Finally, @bhvieira mentioned [docs/src/data/onehot.md](docs/src/data/onehot.md) which also needs to be updated to use `0` and `1` instead of `false` and `true`. I'd recommend making those docstrings doctests as well by placing `jldoctest` after the initial backticks instead of `julia` or nothing, like this:

    ```jldoctest
    julia> onehot(:a, [:a, :b, :c])
    [...]
    ```

That way, these kinds of mistakes should not happen. Sorry I made them.

**Comment by janEbert** [comment]
Hey @Dsantra92, friendly ping in case you forgot about this.

**Comment by Dsantra92** [comment]
Sorry I really got busy with college work and thank you for the reminder @janEbert .I will be working on it from today.

**Comment by janEbert** [comment]
No need to apologize at all. :)
I just don't want to confuse more people with my mistake. So, thanks that you're going to fix it!

**Comment by Dsantra92** [comment]
@janEbert I have commited the changes to one hot function that you requested.

**Comment by janEbert** [comment]
Thank you so much!

**Comment by Dsantra92** [comment]
Already merged in #1256

**Pull request closed without merging**
