### PR TITLE
Re: Feature : Some optimizers added

### PR DESCRIPTION
**Pull request by sriyash421**
Added the following function optimizers :

- Rprop
- HeavyBall

Re: #1063

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
I would appreciate doing a sanity check on whether we are doing the right thing by comparing the output from PyTorch for example.

**Comment by dhairyagandhi96** [comment]
I would appreciate doing a sanity check on whether we are doing the right thing by comparing the output from PyTorch for example.

**Comment by sriyash421** [comment]
> I would appreciate doing a sanity check on whether we are doing the right thing by comparing the output from PyTorch for example.

I'll try and compare the gradients across the two.

**Comment by ToucheSir** [comment]
If this is still being pursued, the optimizers should probably be PR'ed against Optimisers.jl. I will say that neither has come up on GitHub, Discourse, Zulip or Slack (to my recollection) outside of this PR.

**Comment by CarloLucibello** [comment]
closing for inactivity

**Pull request closed without merging**
