### PR TITLE
Fixed ExpDecay

### PR DESCRIPTION
**Pull request by thebhatman**
This patch is regarding issue https://github.com/FluxML/Flux.jl/issues/684. The credit goes to @gustafsson for pointing this out.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Is there a test we can add here?

**Comment by dhairyagandhi96** [comment]
We should add a test in here, but otherwise lgtm

**Comment by thebhatman** [comment]
I have added tests for Exponential Decay.

**Comment by dhairyagandhi96** [comment]
How about logging when the decay happened and comparing it with a known ground truth. Also probably a good idea to check that the clip value is honoured.

**Comment by thebhatman** [comment]
Yes. I shall do that. But I did not understand the part about the known ground truth. What will be the ground truth?

**Comment by dhairyagandhi96** [comment]
The ground truth for our purposes can be
A. An array of steps of decay (eg. decay should happen every 1000 steps, so an array along the lines of 1000:1000:10000)
B. We have to honor the clip, so assuming we do enough iterations (10^5 is plenty) we would hit the clip and go beyond. We have to ensure that once the clip is hit, we don't make any further decay, so the ground truth will be the decay parameter we provided.

**Comment by dhairyagandhi96** [comment]
Thanks @thebhatman, this looks great

**Comment by thebhatman** [comment]
Thank you for your help!!!

**Pull request merged**
