### PR TITLE
update documenter

### PR DESCRIPTION
**Pull request by CarloLucibello**

### CODE REVIEW

**Comment by CarloLucibello** [comment]
According to 
https://discourse.julialang.org/t/ann-documenter-0-24/31381
I was expecting to see a preview at 
https://fluxml.ai/Flux.jl/previews/PR1065
but the link is broken

Also, for some reason
https://fluxml.ai/Flux.jl/dev/
didn't catch up with the latest changes in documentation

**Comment by johnnychen94** [comment]
The problem is, I didn't see a CI stage for Documentation here... and not in previous commits.

**Comment by CarloLucibello** [comment]
but we do have have one in travis :confused: 
https://github.com/FluxML/Flux.jl/blob/master/.travis.yml

**Comment by johnnychen94** [comment]
I think I find the issue, am fixing

**Comment by johnnychen94** [comment]
I prefer the previous sidebar style :P

**Comment by johnnychen94** [comment]
`flux.css` seems to be ignored by Documenter v0.24

cf: custom theme https://github.com/JuliaDocs/Documenter.jl/pull/1250

**Pull request merged**
