### PR TITLE
New Optimiser Docs

### PR DESCRIPTION
**Pull request by dhairyagandhi96**
These docs are a WIP version of some of the changes made to the optimisers. Feedback welcome.

Ref: #475

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
I have to fix the first bit of `optimisers.md` still, that's a bit of a mess.

**Comment by MikeInnes** [comment]
I think there are two separate things here:

(1) updating the deprecated syntax in the current docs and
(2) adding docs on the new internal interface and how optimisers can be built.

I think it'd be useful to split those PRs and do (1) first; that's a bit easier to review and we can just get a release out then.

**Comment by dhairyagandhi96** [comment]
I believe the current state should suffice (1). 

Could remove docstrings for consistency as well

**Comment by MikeInnes** [comment]
Thanks a lot @dhairyagandhi96. Now this is merged we can look at expanding the docs with details on the new functionality.

**Comment by dhairyagandhi96** [comment]
Absolutely!

**Pull request merged**
