### PR TITLE
Added Local Contrast Normalization.

### PR DESCRIPTION
**Pull request by sanskar107**

### CODE REVIEW

**Comment by CarloLucibello** [comment]
maybe a more explicative name rather than LCN?

**Comment by MikeInnes** [comment]
Looks good but needs some tests. Also, the current implementation does not seem very GPU-friendly; is there any way to vectorise it more?

**Comment by ToucheSir** [comment]
#312 and #193 were added around the same time and have both been closed for inactivity. Shall we close this as well?

**Comment by CarloLucibello** [comment]
yes, this is definitely the wrong approach in any case.

**Pull request closed without merging**
