### PR TITLE
fx norm deprecation

### PR DESCRIPTION
**Pull request by CarloLucibello**
fix some deprecations for the normalization layers

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Seems fine, but it should follow the guidelines of being faithful to the fields (lambda comes first etc) and should only populate the new fields with the same defaults as the regular constructors

**Comment by CarloLucibello** [comment]
> Seems fine, but it should follow the guidelines of being faithful to the fields (lambda comes first etc)

It's a deprecation, so it should match the old constructor on one side and the new one on the other side

> and should only populate the new fields with the same defaults as the regular constructors

It's a deprecation, so it should match the old behavior

**Comment by DhairyaLGandhi** [comment]
Right, the new constructor should only add the new fields, not change the order of the remaining ones.

**Comment by CarloLucibello** [comment]
> Right, the new constructor should only add the new fields, not change the order of the remaining ones.

This seems rather arbitrary. 

Number of channels is the very first (and typically the only) argument we pass to the user-facing constructor, `BatchNorm(64)`, so seems natural to have it as the first field in the struct definition, other's fields positions are just shifted by one.

**Comment by DhairyaLGandhi** [comment]
These are different constructors though. They are different from the channel one.

**Comment by CarloLucibello** [comment]
These are just the constructors implicitly defined by the types

**Comment by DhairyaLGandhi** [comment]
Yes they are defined per our struct definition. They are convenient for when someone wants to use different array or number types.

**Comment by CarloLucibello** [comment]
moved the number of channels in last position

**Comment by CarloLucibello** [comment]
should be ready to merge @DhairyaLGandhi

**Review by DhairyaLGandhi — APPROVED** [review]
We will probably want the depwarns in rather quickly. Hopefully we can resolve the fields situation, it's a pretty long list atm

bors r+

**Pull request merged**
