### PR TITLE
Make `rng_from_array` non differentiable

### LINKED ISSUE #2062: Make `rng_from_array` non-differentiable
Using this like:
```julia
function mylayer(x)
    rng = rng_from_array(x)
    ...
end
```
will try to propagate gradients through which we don't want.

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Fixes #2062 

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable

### CODE REVIEW

**Review by ToucheSir — APPROVED** [review]
Thanks! Could you add a quick test which uses this with `gradient`?

**Comment by Saransh-cpp** [comment]
How can I check whether the `gradient` is propagating through `rng_from_array`? I have something like right now - 
```julia
@test "rng_from_array" begin
  m(x) = (rand(rng_from_array(x)) * x)[1]
  gradient(m, ones(2))
end
```
but I am not sure if this is testing anything concrete?

**Comment by ToucheSir** [comment]
That should be fine. We just need something that will complain if the non-differentiability breaks down at some point.

**Comment by Saransh-cpp** [comment]
Thanks, @ToucheSir! This should work.

**Review by ToucheSir — APPROVED** [review]
LGTM

**Pull request merged**
