### PR TITLE
Adapt to changes in NNlib to use `mode` externally

### PR DESCRIPTION
**Pull request by ayush1999**
This works on the changes made in https://github.com/FluxML/NNlib.jl/pull/53 . 
(To use mode directly from Flux).

### CODE REVIEW

**Comment by MikeInnes** [comment]
I think the API needs some thought here, and I'd rather not 0/1 (which are unclear to read). Maybe a kwarg like `reflect=true`?

I'm almost tempted to just have a separate `CrossCorrelation` layer for this, but it's probably not worth that.

**Comment by ayush1999** [comment]
@MikeInnes I've added  `reflect` as an attribute of `Conv`. When `true`, reflects internally acts similar to `mode=0`.

**Comment by philtomson** [comment]
It seems like convolution mode should be the default with cross correlation as the option.

**Comment by MikeInnes** [comment]
I believe we already do; `mode = 0` corresponds to convolution in CUDNN.

**Comment by ayush1999** [comment]
@philtomson The nomenclature is actually a bit confusing. `Convolution` means flipping the kernel and then adding the element wise products. `Cross Correlation` is the same as Convolution, but without flipping the kernel. Flux by default flips the kernel, and hence does Convolutions. I think it'd be better to have a kwarg with `mode="convolution"` or `mode="cross-correlation"`, so that there isn't any confusion.

**Comment by philtomson** [comment]
Yeah, I don't like plain strings for these kinds of things (It's all the rage in Python-land, but I think we can do better).

It would be good if it was some kind of enum type, I think you can do this with @enum:

`@enum Choice convolution correlation`

**Comment by MikeInnes** [comment]
Are we doing #423 instead?

**Comment by ayush1999** [comment]
Yes, there was a plan to add an option to `Conv` initially, but that changed later. Closing this.

**Pull request closed without merging**
