### PR TITLE
Sparse optimization, printing fixes

### LINKED ISSUE #1354: Broken methods(Base.show)
https://github.com/FluxML/Flux.jl/blob/master/src/data/tree.jl#L17
`Base.show(io::IO, t::Type{Tree{T}}) where T = print(io, "Tree{", T, "}")`
has broken printing, the method can't be printed.

### LINKED ISSUE #1355: Usage of OneHotMatrix for input to neural network is very slow.
Multiplication of OneHotMatrix by dense layer could be more optimized, e.g. by
```julia
using LinearAlgebra
function Base.:*(A::AbstractMatrix, B::Flux.OneHotMatrix)
	m = size(A,1)
	Y = similar(A, m, size(B,2))
	for (j,ohv) in enumerate(B.data)
		ix = ohv.ix
		for i in 1:m
			@inbounds Y[i,j] = A[i,ix]
		end
	end
	Y
end
function Base.:*(A::AbstractMatrix, B::Adjoint{Bool,<: Flux.OneHotMatrix})
	m = size(A,1)
	Y = similar(A, m, size(B,2))
	Y .= 0
	BT = B'
	for (j,ohv) in enumerate(BT.data)
		ix = ohv.ix
		for i in 1:m
			@inbounds Y[i,ix] += A[i,j]
		end
	end
	Y
```

should I make PR for this?

### PR DESCRIPTION
**Pull request by racinmat**
- [x] Tests are added
- [x] Entry in NEWS.md
- [ ] Documentation, if applicable
- [ ] Final review from `@dhairyagandhi96` (for API changes).

No API change here, only bugfixes and optimizations.
Fixes #1355  
Fixes #1354 
Removed workaround of https://github.com/JuliaGPU/CuArrays.jl/issues/676 because Flux is not using CuArrays now. (and it collides with speedup of OneHotMatrix)
Added more tests of normalization of empty arrays.

Could this PR be labeled by `hacktoberfest-accepted`?
Thanks.

### CODE REVIEW

**Comment by racinmat** [comment]
@DhairyaLGandhi

**Comment by racinmat** [comment]
Here are benchmarks. I renamed this new method to `mul_faster` for sake of benchmarks.
Results are very significant.
```julia
using BenchmarkTools, LinearAlgebra
x = rand(Float32, 100, 50)
y = Flux.onehotbatch(ones(100), 1:50)
@btime x*y
@btime Flux.mul_faster(x, y)
x = rand(Float32, 100, 100)
y = Flux.onehotbatch(1:100, 1:100)
@btime x*y
@btime mul_faster(x, y)
```
prints
```
405.699 μs (8 allocations: 39.47 KiB)
2.411 μs (2 allocations: 39.14 KiB)
836.201 μs (8 allocations: 39.47 KiB)
2.562 μs (2 allocations: 39.14 KiB)
```
two orders of magnitude faster.

**Comment by CarloLucibello** [comment]
Hi, thanks for this. Could you file a separate PR for each fix?
Also, do not update the Manifest as it creates noise. 
Let's also create a `benchmarks` folder and put the onehot benchmark there

**Comment by racinmat** [comment]
thanks for response, ok, will do

**Comment by racinmat** [comment]
Added first PR here #1368

**Comment by racinmat** [comment]
@CarloLucibello  Would it make sense to do separate PR for removing these trailing spaces at end of lines? 
I know it's a small thing, but I think they should not be here. I have the changes ready, all in single commit, but I want to ask before I create PR for this.

**Comment by CarloLucibello** [comment]
sure, why not

**Comment by CarloLucibello** [comment]
@racinmat can this be closed?

**Comment by racinmat** [comment]
Yes, I'll make separate PR for this with proper tests and benchmarks.

**Pull request closed without merging**
