### PR TITLE
Make really good clear examples and explination of @functor  in docs

### PR DESCRIPTION
**Pull request by findmyway**

### CODE REVIEW

**Comment by johnnychen94** [comment]
Thanks for the explanation! Should be enough to close #1056

It would be fantastic if there's some brief docstring to `@functor` 😄

**Comment by CarloLucibello** [comment]
@findmyway I started to add docstrings to the `functor.jl` file, then I recalled about this PR. Please fill free to take/adapt anything you want from #1068 to add here, even all of it.

**Comment by findmyway** [comment]
I just switched the base branch from master to your PR directly, in case you need to update the docs further 😃

**Comment by ToucheSir** [comment]
@CarloLucibello seems like this fell off the map and never made it into master? Would it be possible to cherry-pick this commit? The [current docs](https://fluxml.ai/Flux.jl/stable/gpu/) don't mention functors at all!

(happy to put in a PR for this)

**Comment by DhairyaLGandhi** [comment]
Yeah, i think putting up the PR a clear example of functor would be good. The motivation may not need to define the internals of the `functor` function etc. Just a thought

**Comment by ToucheSir** [comment]
I stand corrected, there was already a nice explanation on https://fluxml.ai/Flux.jl/stable/models/advanced/ and I just wasn't finding it through the docs search. Mea culpa :)

**Pull request merged**
