### PR TITLE
Added PixelShuffle Operation

### PR DESCRIPTION
**Pull request by shreyas-kowshik**
Added Pixel Shuffle Operation used frequently in super-resolution networks for up-sampling.

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
I think this makes more sense as a function. We aren't exactly storing any parameters, so as long as the Ops are differentiable, we should be good.

**Comment by shreyas-kowshik** [comment]
@dhairyagandhi96 So where do you suggest moving this file to? I had initially modified `conv.jl` thinking it would make more sense to put it in there as all convolution related functions would be together.

**Comment by dhairyagandhi96** [comment]
I would put this in perhaps in NNlib.jl.

**Comment by shreyas-kowshik** [comment]
@dhairyagandhi96 Added it here : https://github.com/FluxML/NNlib.jl/pull/112

**Comment by ToucheSir** [comment]
We can close this now that #1468 is merged :)

**Pull request closed without merging**
