### PR TITLE
optimization of normalisation by passing mean

### LINKED ISSUE #1295: Unnecessarily slow normalisation, twice calculating mean
https://github.com/FluxML/Flux.jl/blob/v0.11.0/src/layers/stateless.jl#L23 does not specify mean, although it was specifying it in previous version. 
There is a note `# use this when #478 gets merged`
https://github.com/FluxML/Flux.jl/issues/478 is an issue closed by https://github.com/FluxML/Flux.jl/pull/479 which is merged. Should I send a PR to use the version passing mean?

### PR DESCRIPTION
**Pull request by racinmat**
Fixes #1295 .

Is the Entry in NEWS.md needed in this case, or not?

### PR Checklist

- [x] Tests are already there
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable
- [ ] Final review from `@dhairyagandhi96` (for API changes).

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
This breaks with CUDA.

**Comment by DhairyaLGandhi** [comment]
Thanks!

bors r+

**Comment by racinmat** [comment]
Looks like it's crashing due to inability to download datasets.

**Comment by racinmat** [comment]
@DhairyaLGandhi could you merge this, please?

**Comment by CarloLucibello** [comment]
This will give wrong gradients until https://github.com/FluxML/Zygote.jl/pull/478 is merged

**Comment by racinmat** [comment]
Oh, I see, thanks.

**Comment by CarloLucibello** [comment]
we have to wait until the Zygote error is fixed befor doing it, I'll close this for now

**Pull request closed without merging**
