### PR TITLE
add NNlib docs + misc docs improvements

### PR DESCRIPTION
**Pull request by CarloLucibello**
Partially addressing https://github.com/FluxML/NNlib.jl/issues/137.

Also, I'm leaving out the `σ`  activation and using its alias `sigmoid`, since `σ` conveys little information and it is also used to denote a generic activation in the Dense layer. I think we should deprecate `σ` in NNlib, has this been discussed already?

In an ideal world, before merging this, we should get NNlib to either unexport or add docs to its undocumented exports

### CODE REVIEW

**Comment by CarloLucibello** [comment]
I chose to expose in the documentation only a subset, which should be the most relevant to users, of the functions exported by Flux and re-exported by NNlib (most of which are undocumented in any case). 

We should for https://github.com/FluxML/NNlib.jl/pull/172 to be merged  before merging this PR

**Comment by CarloLucibello** [comment]
This is ready for review. We should wait for the new release of NNlib before merge

**Comment by dhairyagandhi96** [comment]
Can you rebase on master please?

**Comment by dhairyagandhi96** [comment]
Ah, the log and exp bugs showing up in GitLab.

**Comment by CarloLucibello** [comment]
ah, is current master broken? How do we fix it?

**Comment by dhairyagandhi96** [comment]
I would do a run with Zygote master to see if we caught the codepath with the recent changes there

**Comment by CarloLucibello** [comment]
> I would do a run with Zygote master to see if we caught the codepath with the recent changes there

how do we do that?

**Comment by CarloLucibello** [comment]
how do we get rid of these cuda exp errors?

**Comment by CarloLucibello** [comment]
@maleadt any hint on this?

**Comment by CarloLucibello** [comment]
it should work now

bors r+

**Pull request merged**
