### PR TITLE
Bump version to 0.10.4

### PR DESCRIPTION
**Pull request by ararslan**
Since 0.10.3, the only changes have been dependency compatibility bumps, new features, and documentation improvements. See https://github.com/FluxML/Flux.jl/compare/v0.10.3...master.

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
Actually, since cuarrays 2.x is julia 1.3 and up, we'll need to drop 1.0 support to update this one...

**Comment by ararslan** [comment]
Seems Flux isn't being tested on 1.0 anyway: https://github.com/FluxML/Flux.jl/blob/master/.travis.yml#L9. And I believe there was a change to package registration that allows bumping the patch when dropping a Julia version. I'd personally vote for dropping 1.0, but of course this is a decision for the Flux maintainers. 🙂

**Comment by ararslan** [comment]
Actually, Flux as-is won't work on 1.0 anyway; it seems to be using some features introduced in later minor releases, e.g. `isnothing` [here](https://github.com/FluxML/Flux.jl/blob/master/src/layers/normalise.jl#L57).

**Comment by dhairyagandhi96** [comment]
Fair cop, we should at least set the Julia version correctly, could you bump the Julia version required?

**Comment by ararslan** [comment]
Done. Set to 1.3 to reflect the updated requirement due to the CuArrays dependency.

**Comment by ararslan** [comment]
Also have a companion PR to Zygote to update it for CuArrays 2: https://github.com/FluxML/Zygote.jl/pull/565

**Pull request closed without merging**
