### PR TITLE
DOC: resolve undefined error in basic models

### PR DESCRIPTION
**Pull request by stsievert**
**What does this PR implement?**
I tried copy/pasting the code from https://fluxml.ai/Flux.jl/stable/models/basics/, but ran into an undefined error. This resolves that.

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
Hmm, that's weird, since `params` is exported, it shouldn't show that behaviour. Works fine for me on latest release (v0.7.3) and master. Maybe check the environment for conflicts?

**Comment by stsievert** [comment]
Huh, it looks like there's an issue with the documentation rendering.

This is the raw code in `basics.md` (which runs fine for me):

    ```jldoctest basics
    julia> using Flux

    julia> W = param(2)
    2.0 (tracked)

    julia> b = param(3)
    3.0 (tracked)

    julia> f(x) = W * x + b;

    julia> grads = Tracker.gradient(() -> f(4), Flux.params(W, b));

    julia> grads[W]
    4.0

    julia> grads[b]
    1.0
    ```

However, the documentation is rendered as

screen shot 2019-02-25 at 11 45 23 am

It's missing the `using Flux`.

**Comment by MikeInnes** [comment]
Ah, this is just due to the docs being updated since the most recent release. You can see the fixed version on the [dev branch](https://fluxml.ai/Flux.jl/dev/models/basics/). Bit unfortunate but will be fixed after the next tag.

**Comment by stsievert** [comment]
> Ah, this is just due to the docs being updated since the most recent release.

Sounds good, and I'll close this PR.

**Pull request closed without merging**
