### PR TITLE
WIP: svd back propagation

### PR DESCRIPTION
**Pull request by GiggleLiu**
back propagation in Issue #472 
TODO:
- [ ] GPU support, now `gesvd!` in `CuArray.jl` is buggy, let us be patient.
- [ ] change numeric gradient check in test
- [ ] change file structure, now I put `svd.jl` under layers, which is not proper

### CODE REVIEW

**Comment by MikeInnes** [comment]
Cool, thanks! I think this could go under `tracker/lib` (where we already have some linalg definitions).

Would appreciate a look-over from someone who knows about these things.

**Comment by jgreener64** [comment]
This PR is useful, any chance of getting it merged?

**Comment by GiggleLiu** [comment]
So far, this PR only work for CPU. It should be polished for GPU, I am waiting for the JSoC project of porting MAGMA. Also, I have a newer version that supports complex valued input, that should also be updated in this PR.

**Comment by dhairyagandhi96** [comment]
Some things need to be ported to Tracker.jl so a parallel PR there would be awesome.

**Comment by GiggleLiu** [comment]
For someone who needs `svd`, `qr`, `lq` and symmetric `eigen` autodiff in urgent.
Here is a unregistered package that implements these functions based on `Zygote`:
https://github.com/GiggleLiu/LinalgBackwards.jl

These functions are well tested for complex numbers, but does not support GPU for the moment. It basically implements this blog: https://giggleliu.github.io/2019/04/02/einsumbp.html

NOTE: This package is only for development, later, it will probably be merge to `Flux`.

**Pull request closed without merging**
