### PR TITLE
Conv constructor type mismatch fix

### PR DESCRIPTION
**Pull request by AShedko**
This fixes the type mismatch in a constructor for Conv op.

Found when trying to create a 1d convolution like so:
```
c = Conv(Tuple(7),300=>128)
```
Which results in the following error:
```
MethodError: no method matching Conv(::TrackedArray{…,Array{Float32,3}}, 
::TrackedArray{…,Array{Float64,1}}, ::typeof(identity); stride=1, pad=0, dilation=1) ...
```
The important parts are :TrackedArray{…,Array{**Float32**,3}}, and ::TrackedArray{…,Array{**Float64**,1}}

### CODE REVIEW

**Comment by AShedko** [comment]
@MikeInnes, PTaL

**Comment by MikeInnes** [comment]
The example you posted works OK for me.

**Comment by AShedko** [comment]
Weights are initialized with Float64 on CPU, is that an error?
No GPU atm, so I cannot check.

**Comment by ToucheSir** [comment]
Looks like this is from the Tracker era and can be closed.

**Pull request closed without merging**
