### PR TITLE
Fix the last remaining 404 errors

### PR DESCRIPTION
**Pull request by Saransh-cpp**
The only thing keeping me from making the cross reference check strict -
```julia
strict = [:cross_references]
```
is the failing `isnumeric` hyperlink (https://fluxml.ai/Flux.jl/stable/training/optimisers/#Optimisers.destructure), which does not have a docstring in `Optimisers.jl`.

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable

### CODE REVIEW

**Comment by ToucheSir** [comment]
Nice! @mcabbott should we slap a docstring onto `isnumeric` or scrub the dangling reference to it in https://github.com/FluxML/Optimisers.jl/blob/9b75dbb0d80e4e383eab279345a70d4b567721ea/src/destructure.jl#L8?

**Comment by mcabbott** [comment]
Could go either way. I made https://github.com/FluxML/Optimisers.jl/pull/104 to see how it looks.

**Comment by Saransh-cpp** [comment]
I will fix the reference here once https://github.com/FluxML/Optimisers.jl/pull/104 is merged!

**Review by mcabbott — APPROVED** [review]

**Comment by Saransh-cpp** [comment]
Temporarily fixed the references for the API of `OneHotArrays.jl`. See #2038.

**Comment by ToucheSir** [comment]
If you wouldn't mind looking into the doctest failure, we can get this merged.

**Comment by Saransh-cpp** [comment]
- The regex pattern is getting out of hand 😅 but now it captures `Float32` values too (which were causing the CI to fail).
- `Documenter.jl` was outdated and was not allowing `strict` to be of the type `Vector{Symbol}`.

I think a new release for `Optimisers.jl` is required for the tests to pass. The CI is still not picking up the docstring for `Optimisers.isnumeric`.

**Comment by ToucheSir** [comment]
> I think a new release for `Optimisers.jl` is required for the tests to pass. The CI is still not picking up the docstring for `Optimisers.isnumeric`.

Ok, I was wondering why it worked given that wasn't tagged! Have another try after https://github.com/JuliaRegistries/General/pull/66169.

**Comment by Saransh-cpp** [comment]
> Have another try after https://github.com/JuliaRegistries/General/pull/66169.

Everything works now!

**Review by ToucheSir — APPROVED** [review]
Great!

**Pull request merged**
