### PR TITLE
Fix binarycrossentropy on CuArrays

### PR DESCRIPTION
**Pull request by janEbert**
Ref #889.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Thanks @janEbert!

bors r+

**Comment by MikeInnes** [comment]
Would you mind following up with a quick test also?

**Comment by janEbert** [comment]
Oh sure, sorry that I forgot about that!

**Comment by janEbert** [comment]
Added it.

**Comment by MikeInnes** [comment]
Wonderful, thanks again.

bors r+

**Comment by MikeInnes** [comment]
Getting scuppered by #923. If the error on 1.0 is also present on master, we can just merge this anyway.

**Pull request merged**
