### PR TITLE
Bump AMDGPU.jl compat to 0.7

### PR DESCRIPTION
**Pull request by pxl-th**
### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable

### CODE REVIEW

**Review by mcabbott — APPROVED** [review]

**Comment by pxl-th** [comment]
Can someone please merge it?

**Comment by ToucheSir** [comment]
For future PRs, I believe you should already have merge rights. If something is approved, just go for it :)

**Comment by pxl-th** [comment]
> For future PRs, I believe you should already have merge rights. If something is approved, just go for it :)

Thanks for merging. No, I only have them for NNlib.jl repo.

**Comment by ToucheSir** [comment]
My mistake, we've had so many compat PRs recently with the stdlib change that I thought this was for a different repo!

**Pull request merged**
