### PR TITLE
Update GPU CI.

### PR DESCRIPTION
**Pull request by maleadt**
Dummy changes to test status pushes from BuildKite. Now that it works, remove GitLab CI.

### CODE REVIEW

**Review by CarloLucibello — APPROVED** [review]

**Comment by maleadt** [comment]
Bors isn't required anymore now that BuildKite can do thirt-party PRs. Also note that it was only listening for `gitlab` statuses anyway: https://github.com/FluxML/Flux.jl/blob/ef1aa4927a06a70a2efa679a29ce3615c3e846eb/bors.toml. Either it should be updated to check the BuildKite status, all statusses, or removed altogether.

**Comment by DhairyaLGandhi** [comment]
Thanks so much!

**Comment by CarloLucibello** [comment]
so @DhairyaLGandhi you have to lift the github's restriction, merging is blocked here

**Pull request merged**
