### PR TITLE
Transition to doctests

### PR DESCRIPTION
**Pull request by ayan-b**
Related to https://github.com/FluxML/Flux.jl/issues/561

### CODE REVIEW

**Comment by ayan-b** [comment]
@MikeInnes In travis is doctests running? From the documenter.jl docs: `Documenter will, by default, try to run jldoctest code blocks that it finds in the generated documentation. ` However, I didn't find any specific keyword which will confirm doctests running in travis.

**Comment by ayan-b** [comment]
Please review @MikeInnes . :smile:

**Comment by ayan-b** [comment]
Please review @MikeInnes. :)

**Comment by MikeInnes** [comment]
Looks good, but is there a way to tell that this is running on CI?

**Comment by ayan-b** [comment]
Yup, you can intentionally add some errors and the Ci will throw errors.

**Comment by MikeInnes** [comment]
Alright, sounds good to me then – thanks for the patch.

**Pull request merged**
