### PR TITLE
Removing deprecated method call in `GPU_BACKEND_ORDER`.

### LINKED ISSUE #2312: Warning: `sort(d::Dict; args...)` is deprecated, use `sort!(OrderedDict(d); args...)` instead.
In precompilation, I got:
```julia
┌ Flux [587475ba-b771-5e3f-ad9e-33799f191a9c]
│  ┌ Warning: `sort(d::Dict; args...)` is deprecated, use `sort!(OrderedDict(d); args...)` instead.
│  │   caller = top-level scope at functor.jl:190
│  └ @ Core C:\Users\Hossein Pourbozorg\.julia\packages\Flux\pR3k3\src\functor.jl:190
└
```

### PR DESCRIPTION
**Pull request by codetalker7**
Closes #2312.

### CODE REVIEW

**Review by ToucheSir — APPROVED** [review]
Nice, this is cleaner than my ideas!

**Comment by prbzrg** [comment]
This isn't same as before, it should be `OrderedDict` from `OrderedCollections`.
```julia
julia> const GPU_BACKENDS = ["CUDA", "AMD", "Metal", "CPU"]
4-element Vector{String}:
 "CUDA"
 "AMD"
 "Metal"
 "CPU"

julia> const GPU_BACKEND_ORDER = Dict(collect(zip(GPU_BACKENDS, 1:length(GPU_BACKENDS))))
Dict{String, Int64} with 4 entries:
  "CUDA"  => 1
  "AMD"   => 2
  "CPU"   => 4
  "Metal" => 3

julia> const GPU_BACKEND_ORDER2 = OrderedDict(collect(zip(GPU_BACKENDS, 1:length(GPU_BACKENDS))))
OrderedDict{String, Int64} with 4 entries:
  "CUDA"  => 1
  "AMD"   => 2
  "Metal" => 3
  "CPU"   => 4

```

**Comment by prbzrg** [comment]
on `Flux@0.14.2`:
```julia
julia> Flux.GPU_BACKEND_ORDER
OrderedDict{String, Int64} with 4 entries:
  "CUDA"  => 1
  "AMD"   => 2
  "Metal" => 3
  "CPU"   => 4
```

**Comment by ToucheSir** [comment]
`GPU_BACKEND_ORDER` isn't a part of the public API, nor is its iteration order defined. We're not going to add a package dependency just for this.

**Comment by prbzrg** [comment]
Oh, I was under the impression that the order of it matters because there was a `sort` that caused the deprecation warning.

**Pull request merged**
