### PR TITLE
Fix for broadcast type matching

### PR DESCRIPTION
**Pull request by ayush1999**
Fixes : #260

### CODE REVIEW

**Comment by CarloLucibello** [comment]
What's the cause of #260 ? `BN.λ` being Float64?

**Comment by ayush1999** [comment]
Looks to be the case. @CarloLucibello  Any idea why the build is failing?

**Comment by MikeInnes** [comment]
For ONNX, it seems like it'd be better just to initialise the BatchNorm with f32 when you create it. This is going to add a fair bit of conversion overhead that I'd rather avoid.

**Comment by CarloLucibello** [comment]
closing as stale

**Pull request closed without merging**
