### PR TITLE
Load Juno-specific code conditionally.

### LINKED ISSUE #454: make Juno dependency conditional
Because of a dependency via Juno, using Flux on Julia#master currently suffers from https://github.com/JunoLab/Media.jl/issues/19.

I wonder if dependency on Juno could be made conditional, via Requires. Looking at the code, the only difficulty I see with this is the `@progress` macro in training.

### PR DESCRIPTION
**Pull request by tpapp**
Use the new JunoProgressLogger API for the progress bar via @logmsg.

Fixes #454.

### CODE REVIEW

**Comment by tpapp** [comment]
@pfitzseb, can you please review if I am using the progressbar API right?

**Comment by pfitzseb** [comment]
You'll also need to set the `_id` kwarg to a constant string or symbol to associate the different `@logmsg`s.

Could also completely get rid of Juno by using the TreeViews.jl API for displaying results instead, but that's probably out of scope for this PR.
Looks good otherwise.

**Comment by tpapp** [comment]
@MikeInnes: please let me know if there is anything else I can improve in this PR to get it merged.

**Comment by tpapp** [comment]
Is there a chance of merging this? If not, should I make a PR along some alternative lines? With #454, Flux is difficult to use on `master`.

**Comment by MikeInnes** [comment]
Can you try `] add Media#mji/dynamic`?

**Comment by MikeInnes** [comment]
Media is fixed and tagged now, so this shouldn't be necessary.

**Pull request closed without merging**
