### PR TITLE
Release 0.11.5

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
bors try

**Comment by DhairyaLGandhi** [comment]
Okay looking at the Gitlab run; and releasing after.

**Comment by clad26** [comment]
I guess we've to change the version in Project.toml from 0.12-dev to 0.11.5, before releasing this?

**Comment by clad26** [comment]
@DhairyaLGandhi 

> I guess we've to change the version in Project.toml from 0.12-dev to 0.11.5, before releasing this?

Should I make the change in https://github.com/FluxML/Flux.jl/pull/1477?

**Comment by CarloLucibello** [comment]
I don't think this is  the correct way of tagging v0.11 releases: this should have been merged in the branch `release-v0.11`, then the branch should have been tagged

**Review by CarloLucibello — APPROVED** [review]

**Pull request merged**
