### PR TITLE
Change check for CUDNN availability.

### PR DESCRIPTION
**Pull request by maleadt**
`libcudnn` is an implementation detail; check for the module.

### CODE REVIEW

**Comment by maleadt** [comment]
Ah, I failed to notice that `cudnn.jl` contains quite some manual API calls to `libcudnn` so it did make sense to check for that. Although those API calls should probably move to CuArrays.CUDNN?

**Comment by MikeInnes** [comment]
I'd be fine with moving that stuff to CuArrays in principle; should just be a copy-paste really.

**Comment by MikeInnes** [comment]
I think this is outdated since #473.

**Comment by MikeInnes** [comment]
I think we'll want to move more of this stuff to CuArrays  anyway (so that we can share it between Flux and Knet), so I'll make that happen in the near future.

**Pull request closed without merging**
