### PR TITLE
make PackageCompiler happy

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
cc @CarloLucibello I have made the same changes to the deprecations PR as well

@willtebbutt I wanted to make a release with this change too

### CODE REVIEW

**Comment by CarloLucibello** [comment]
this is not updating the Zygote bound. The correct way to do this would have been to push these changes to #1451 , which is then merged in a `release-v0.11` branch, which is than tagged. 
I'll update #1451 for a 0.11.4 release

**Comment by DhairyaLGandhi** [comment]
That's correct, I just made an update to the current release. The depreciation pr I was referring to is #1442

**Comment by DhairyaLGandhi** [comment]
Great so this pr needs to be merged into release-v0.11 instead. I was searching for the correct name

**Comment by CarloLucibello** [comment]
so? are you going to merge this there?

**Comment by DhairyaLGandhi** [comment]
Done, should I merge it now?

**Comment by CarloLucibello** [comment]
yes, I'll rebase #1451 on top

**Pull request merged**
