### PR TITLE
Work around GPU launch bug for BatchNorm

### PR DESCRIPTION
**Pull request by staticfloat**
X-ref: https://github.com/FluxML/Flux.jl/issues/385

### CODE REVIEW

**Comment by MikeInnes** [comment]
Julia's escape analysis can make for some fun gpu debugging.

Do we have a test that catches this?

**Comment by staticfloat** [comment]
Yes; here you go:

```julia
using CuArrays, Flux
μ = gpu(randn(Float32, 1, 1, 8, 1)); σ = μ; β = param(μ); γ = param(μ);
x = gpu(randn(Float32, 10, 10, 8, 1))
γ .* ((x .- μ) ./ σ) .+ β # <--- This should error out
```

**Comment by MikeInnes** [comment]
Actually, I guess this is not escape analysis but some failure of broadcast compilation when it gets this complex.

That's useful but also, does this issue get caught by the flux gpu tests now? If not we should just add something that calls batchnorm.

**Comment by KristofferC** [comment]
This content of this PR is in #586, can be closed.

**Comment by staticfloat** [comment]
Great, thanks @KristofferC!

**Pull request closed without merging**
