### PR TITLE
use Functors 0.3 in Flux

### PR DESCRIPTION
**Pull request by mcabbott**
After https://github.com/FluxML/Functors.jl/pull/33, shared weights which are wrapped in `Transpose` etc. will be seen as shared by Functors.jl, this PR updates Flux.jl to match:
```julia
julia> mat = [1 2; 3 4.0];

julia> Flux.params((mat, mat'))  # previously saw two arrays
Params([[1.0 2.0; 3.0 4.0]])
```
~~Should probably have tests, opened now just to run CI.~~

Closes #2010

### PR Checklist

- [x] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable

### CODE REVIEW

**Comment by mcabbott** [comment]
This has a side-effect of messing up pretty-printing, if you have transposed arrays within layers:
```julia
julia> enc = Chain(Dense(40 => 20, tanh), Dense(20 => 10));

julia> dec = Chain(Dense(enc[1].weight', true, tanh), Dense(enc[2].weight', true, tanh));

julia> model = Chain(; enc, dec)
Chain(
  enc = Chain(
    Dense(40 => 20, tanh),              # 820 parameters
    Dense(20 => 10),                    # 210 parameters
  ),
  dec = Chain(
    Dense(
      Float32[0.0127840545 0.05094894 … 0.066639684 -0.18354462; -0.26546717 0.05784449 … 0.19263656 0.2704237; … ; 0.08902565 -0.1931235 … 0.19946606 0.08047413; -0.31344065 0.1451594 … 0.3059671 -0.2995005],  # 800 parameters
      Float32[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 40 parameters  (all zero)
      tanh,
    ),
    Dense(
      Float32[0.008731068 0.44285944 … -0.081168234 -0.02486435; -0.1165446 0.0013048649 … -0.31936178 0.102868944; … ; 0.38076133 -0.28559396 … -0.23577932 -0.14623517; 0.0013932029 0.2429123 … 0.11779807 -0.30120552],  # 200 parameters
      Float32[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 20 parameters  (all zero)
      tanh,
    ),
  ),
)         # Total: 6 trainable arrays, 1_090 parameters,
          # plus 2 non-trainable, 1_000 parameters, summarysize 4.820 KiB.
```
Example from https://github.com/FluxML/Optimisers.jl/pull/42 . That PR has many tests of such models. We could duplicate some of them here, to check that Flux.Optimise treats things right. But perhaps since that's about to be thrown out, it's not worth it.

**Comment by ToucheSir** [comment]
I thought the messed up example reflected the present state of the PR instead of an earlier commit, but the fix + test look good. Buildkite error looks very real though.

**Comment by mcabbott** [comment]
Oh right, sorry. I meant to look at that GPU test.

**Comment by mcabbott** [comment]
Finally looked at this. What a dumb test, here's the weird behaviour it's carefully trying to preserve:
```julia
julia> a = randn(Float32, 4, 4);

julia> gradient(x -> sum(abs, cpu(x)), a')[1]
4×4 adjoint(adjoint(::Matrix{Float32})) with eltype Float32:
  1.0   1.0   1.0   1.0
 -1.0   1.0   1.0   1.0
  1.0  -1.0  -1.0  -1.0
 -1.0   1.0  -1.0  -1.0
```

**Comment by mcabbott** [comment]
This should be ready to go, I think.

**Review by ToucheSir — APPROVED** [review]

**Pull request merged**
