### PR TITLE
Fix `train!` doc string 404

### PR DESCRIPTION
**Pull request by logankilpatrick**

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Closes #1745

**Comment by logankilpatrick** [comment]
I think this is right since `train!` does not actually exist, it is https://fluxml.ai/Flux.jl/stable/training/training/#Flux.Optimise.train!

**Comment by logankilpatrick** [comment]
From the [Documenter.jl docs](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@ref-link):
> Note that depending on what the CurrentModule is set to, a docstring @ref may need to be prefixed by the module which defines it.

**Comment by DhairyaLGandhi** [comment]
It should be exported from the Optimise submodule, and therefor in the Flux namespace? Either way, we can include this for the time being.

**Pull request merged**
