### PR TITLE
[ISSUE 1939] Update workflow, to only generate coverage for a specific entry 

### LINKED ISSUE #1939: Only generate and upload coverage for one matrix entry
Config option: https://github.com/julia-actions/julia-runtest/blob/161c97cbc529b36fae585928ed5db05b00fdf2bc/action.yml#L13-L15

Example of conditional logic: https://github.com/FluxML/Zygote.jl/blob/master/.github/workflows/ci.yml#L59-L64

We should do this for all applicable repos in FluxML.

### PR DESCRIPTION
**Pull request by skyleaworlder**
Close #1939 

Add the same condition like [FluxML/Zygote.jl](https://github.com/FluxML/Zygote.jl/blob/master/.github/workflows/ci.yml#L59-L64).

I test workflow in my fork repo:

### 1. push (actually I check this on some other branch)

1. [Julia 1 && Ubuntu-latest](https://github.com/skyleaworlder/Flux.jl/actions/runs/3711165261/jobs/6291322964)

image

2. [Others](https://github.com/skyleaworlder/Flux.jl/actions/runs/3711165261/jobs/6291322890)

image

### 2. PR

1. [Julia 1 && Ubuntu-latest](https://github.com/skyleaworlder/Flux.jl/actions/runs/3711656883/jobs/6292321286)

image

3. [Others](https://github.com/skyleaworlder/Flux.jl/actions/runs/3711656883/jobs/6292321172)

image

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable

### CODE REVIEW

**Comment by ToucheSir** [comment]
Thanks! Looking back through the codebase, I think we'd need to enable coverage for 1.6 as well because the doctests only run on that version: https://github.com/FluxML/Flux.jl/blob/4a2dc27034bd4f18729edc9e1b69906aa783c129/test/runtests.jl#L57. Disabling coverage for non-linux runners still makes sense though. Should be a relatively minimal change :)

**Comment by skyleaworlder** [comment]
> Thanks! Looking back through the codebase, I think we'd need to enable coverage for 1.6 as well because the doctests only run on that version:
> 
> https://github.com/FluxML/Flux.jl/blob/4a2dc27034bd4f18729edc9e1b69906aa783c129/test/runtests.jl#L57

OK! And I just now noticed that:

> We should do this for all applicable repos in FluxML.

Before I update if-condition, I'd like to ask if I need to modify workflows of other repositories in FluxML, which also use `julia-runtest`? (e.g. NNlib.jl and FastAI.jl)

**Comment by skyleaworlder** [comment]
Update it:

image

**Review by ToucheSir — APPROVED** [review]
Thanks! Workflows for other FluxML repos can be updated in follow-up PRs, no rush.

**Pull request merged**
