### PR TITLE
Cuda 3.0 support

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
cc @maleadt , @jonathan-laurent

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
@jonathan-laurent @maleadt could you confirm that this branch works fine for AlphaZero and CUDA 3. And also whether you've tested the subpackage from https://github.com/FluxML/NNlib.jl/pull/286

**Comment by CarloLucibello** [comment]
you can test the NNlibCUDA´s subpackage with
```
(@v1.6) pkg> add https://github.com/FluxML/NNlib.jl:lib/NNlibCUDA
```

**Comment by CarloLucibello** [comment]
It´s a bit tricky to support both julia 1.5 and julia 1.6 at this point (NNlibCUDA requires julia 1.6). Should we drop julia 1.6 support?

**Comment by CarloLucibello** [comment]
It´s a bit tricky to support both julia 1.5 and julia 1.6 at this point (NNlibCUDA requires julia 1.6). Should we drop julia 1.6 support?

**Comment by CarloLucibello** [comment]
the Manifest here is adding CUDA 2.6 actually

**Comment by maleadt** [comment]
Now that we have device overrides, `Base.exp` etc are GPU compatible, so there's a couple of GPU-specific invocations of `exp`, `log`, ... that can go.

**Comment by jonathan-laurent** [comment]
What exactly should I do to test this?

I tried he following without success:
```
]add Flux#dg/cuda16 NNlib#master CUDA@3.0.3
```

**Comment by DhairyaLGandhi** [comment]
You'd need to check out a local copy and instantiate the manifest in the branch. You also need https://github.com/FluxML/NNlibCUDA.jl

**Comment by jonathan-laurent** [comment]
I just tested AlphaZero.jl on this branch but I am getting a Zygote error during the backprop phase.
It doesn't seem to be related to CUDA.jl though.

```
julia> Scripts.test_grad_updates("connect-four")

Initializing a new AlphaZero environment

Generating 5000 some random traces

Starting gradient updates

  Starting learning
  
    Optimizing the loss
    
         Loss       Lv       Lp     Lreg     Linv       Hp    Hpnet
       1.6541   1.1187   0.3265   0.1639   0.0451   1.8915   1.6223
ERROR: Mutating arrays is not supported
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] (::Zygote.var"#409#410")(#unused#::Nothing)
    @ Zygote ~/.julia/packages/Zygote/RxTZu/src/lib/array.jl:65
  [3] (::Zygote.var"#2276#back#411"{Zygote.var"#409#410"})(Δ::Nothing)
    @ Zygote ~/.julia/packages/ZygoteRules/OjfTt/src/adjoint.jl:59
  [4] Pullback
    @ ~/AlphaZero.jl/src/networks/flux.jl:131 [inlined]
  [5] (::typeof(∂(λ)))(Δ::Nothing)
    @ Zygote ~/.julia/packages/Zygote/RxTZu/src/compiler/interface2.jl:0
  [6] Pullback
    @ ~/AlphaZero.jl/src/networks/flux.jl:121 [inlined]
  [7] (::typeof(∂(foreach_flux_node)))(Δ::Nothing)
    @ Zygote ~/.julia/packages/Zygote/RxTZu/src/compiler/interface2.jl:0
  [8] Pullback
    @ ~/AlphaZero.jl/src/networks/flux.jl:123 [inlined]
  [9] (::typeof(∂(foreach_flux_node)))(Δ::Nothing)
    @ Zygote ~/.julia/packages/Zygote/RxTZu/src/compiler/interface2.jl:0
 [10] Pullback
    @ ~/AlphaZero.jl/src/networks/flux.jl:123 [inlined]
 [11] (::typeof(∂(foreach_flux_node)))(Δ::Nothing)
    @ Zygote ~/.julia/packages/Zygote/RxTZu/src/compiler/interface2.jl:0
 [12] Pullback
    @ ~/AlphaZero.jl/src/networks/flux.jl:118 [inlined]
 [13] (::typeof(∂(foreach_flux_node)))(Δ::Nothing)
    @ Zygote ~/.julia/packages/Zygote/RxTZu/src/compiler/interface2.jl:0
 [14] Pullback
    @ ~/AlphaZero.jl/src/networks/flux.jl:129 [inlined]
 [15] (::typeof(∂(regularized_params)))(Δ::Nothing)
    @ Zygote ~/.julia/packages/Zygote/RxTZu/src/compiler/interface2.jl:0
 [16] Pullback
    @ ~/AlphaZero.jl/src/learning.jl:75 [inlined]
 [17] (::typeof(∂(losses)))(Δ::Tuple{Float32, Nothing, Nothing, Nothing, Nothing})
    @ Zygote ~/.julia/packages/Zygote/RxTZu/src/compiler/interface2.jl:0
 [18] Pullback
    @ ~/AlphaZero.jl/src/learning.jl:122 [inlined]
 [19] (::typeof(∂(λ)))(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/RxTZu/src/compiler/interface2.jl:0
 [20] (::Zygote.var"#178#179"{Tuple{NTuple{5, Nothing}}, typeof(∂(λ))})(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/RxTZu/src/lib/lib.jl:194
 [21] #1686#back
    @ ~/.julia/packages/ZygoteRules/OjfTt/src/adjoint.jl:59 [inlined]
 [22] Pullback
    @ ~/AlphaZero.jl/src/networks/flux.jl:82 [inlined]
 [23] (::typeof(∂(λ)))(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/RxTZu/src/compiler/interface2.jl:0
 [24] (::Zygote.var"#69#70"{Zygote.Params, typeof(∂(λ)), Zygote.Context})(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/RxTZu/src/compiler/interface.jl:252
 [25] lossgrads(f::Function, args::Zygote.Params)
    @ AlphaZero.FluxLib ~/AlphaZero.jl/src/networks/flux.jl:73
 [26] train!(callback::AlphaZero.var"#109#111"{Vector{Float32}}, nn::ResNet, opt::Adam, loss::Function, data::Base.Iterators.Take{Base.Iterators.Stateful{Base.Iterators.Flatten{Base.Generator{Base.Iterators.Repeated{Nothing}, AlphaZero.Util.var"#12#13"{AlphaZero.var"#106#108"{ResNet}, Tuple{Matrix{Float32}, Array{Float32, 4}, Matrix{Float32}, Matrix{Float32}, Matrix{Float32}}, Int64, Bool}}}, Tuple{NTuple{5, Any}, Tuple{Nothing, Base.Generator{Vector{Tuple{Matrix{Float32}, Array{Float32, 4}, Matrix{Float32}, Matrix{Float32}, Matrix{Float32}}}, AlphaZero.Util.var"#9#11"{AlphaZero.var"#106#108"{ResNet}}}, Int64}}}}, n::Int64)
    @ AlphaZero.FluxLib ~/AlphaZero.jl/src/networks/flux.jl:81
 [27] batch_updates!(tr::AlphaZero.Trainer, n::Int64)
    @ AlphaZero ~/AlphaZero.jl/src/learning.jl:125
 [28] macro expansion
    @ ./timing.jl:356 [inlined]
 [29] learning_step!(env::Env{AlphaZero.Examples.ConnectFour.GameSpec, ResNet, NamedTuple{(:board, :curplayer), Tuple{StaticArrays.SMatrix{7, 6, UInt8, 42}, UInt8}}}, handler::Session{Env{AlphaZero.Examples.ConnectFour.GameSpec, ResNet, NamedTuple{(:board, :curplayer), Tuple{StaticArrays.SMatrix{7, 6, UInt8, 42}, UInt8}}}})
    @ AlphaZero ~/AlphaZero.jl/src/training.jl:224
 [30] test_grad_updates(exp::Experiment; num_games::Int64)
    @ AlphaZero.Scripts ~/AlphaZero.jl/src/scripts/test_grad_updates.jl:17
 [31] test_grad_updates
    @ ~/AlphaZero.jl/src/scripts/test_grad_updates.jl:10 [inlined]
 [32] #test_grad_updates#21
    @ ~/AlphaZero.jl/src/scripts/scripts.jl:57 [inlined]
 [33] test_grad_updates(s::String)
    @ AlphaZero.Scripts ~/AlphaZero.jl/src/scripts/scripts.jl:57
 [34] top-level scope
    @ REPL[5]:1

```

**Comment by jonathan-laurent** [comment]
AlphaZero.jl works fine with CUDA 3.0 and this branch.

**Comment by DhairyaLGandhi** [comment]
I think this is good to go, anyone have thoughts?

**Comment by CarloLucibello** [comment]
the NNlibCUDA compat bound is missing and the Manifest could be removed. Beside that, looks good!

**Comment by DhairyaLGandhi** [comment]
Thanks, added the bound, and I'd like to keep the manifest around for now, so I think we are good to go here.

**Comment by jonathan-laurent** [comment]
Is the plan to merge this in the next minor release of Flux? (I imagine this cannot be part of a patch release if you are dropping support for Julia <1.6).

**Comment by DhairyaLGandhi** [comment]
Yeah, I was considering merging and releasing it now. Its allowed within semver to limit Julia versions, and we aren't breaking any Flux API so we are good. Any downstream breaking changes would need depending on CUDA explicitly so we are covered with a patch release.

**Comment by DhairyaLGandhi** [comment]
ref https://github.com/FluxML/NNlib.jl/pull/316

**Pull request merged**
