### PR TITLE
Update conv.jl

### PR DESCRIPTION
**Pull request by colbec**
Relax strict equality; mark some constants as Float32 to match existing values

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Is this strictly necessary? Seems like some checks on types matching have also been changed, which seems odd.

**Comment by ToucheSir** [comment]
Yeah, I don't see what the functional purpose of this PR is (i.e. what issue is it fixing). Also comparing functions with `≈` is strictly incorrect.

**Comment by colbec** [comment]
Ok, currently test Flux against master produces warnings about mixing float 32 and float 64 "which might not be what you want". Also on my machine there is one failed test, CrossCor which fails in the test, but copying the test code to my REPL runs fine. I raised the issue in Flux on Slack and was given some advice which I followed. I may have misinterpreted the suggestion in which case I will happily withdraw the PR in favour of something which resolves the issues seen.

**Comment by ToucheSir** [comment]
Right, so as Michael noted on Slack:
> Exact equality is fine for integers like size, of course

The only things that should be tested with `isapprox` here are floating point results, and only those where we're not certain the sequence of calculations on the RHS and LHS aren't the exact same (e.g. if `AdaptiveMaxPool((5,5)) != maxpool(x, PoolDims(x, 2))`, that's a bug). If you run this PR locally, you'll find there are also a bunch of MethodErrors because `≈` is being used for sizes (tuples of ints) and struct types.

Back to the issue at hand though, it seems like the intent was to fix inexact results calculations between `CrossCor` and `Conv`. You can replicate this locally by making `w` a Float32 array, as I believe that triggers the optimized XNNPack path instead of the built-in fallback (and hence the warning you saw).
```julia
julia> isapprox(CrossCor(w[end:-1:1, end:-1:1, :, :], [0.0])(x), Conv(w, [0.0])(x))
false

julia> CrossCor(w[end:-1:1, end:-1:1, :, :], [0.0])(x) .- Conv(w, [0.0])(x)
27×27×1×1 Array{Float64, 4}:
[:, :, 1, 1] =
 -1.19209e-7   0.0          0.0          0.0          0.0         -5.96046e-8   2.98023e-8  -1.19209e-7   1.19209e-7  …   0.0          0.0          5.96046e-8  -5.96046e-8   0.0          0.0          0.0          5.96046e-8
  0.0          0.0          0.0          0.0          0.0          0.0          5.96046e-8   1.19209e-7  -5.96046e-8      0.0          0.0         -5.96046e-8  -5.96046e-8   0.0          1.19209e-7  -5.96046e-8  -1.19209e-7
  0.0          0.0          0.0          0.0          0.0          5.96046e-8   0.0         -2.98023e-8   0.0             1.19209e-7   0.0          0.0          0.0          5.96046e-8  -5.96046e-8   0.0          0.0
  0.0         -5.96046e-8   0.0          0.0          0.0          5.96046e-8   0.0         -2.98023e-8   0.0             0.0          0.0          0.0          5.96046e-8   0.0          0.0          0.0          0.0
  0.0          0.0         -5.96046e-8  -5.96046e-8   0.0          0.0          0.0         -2.98023e-8   0.0             5.96046e-8   0.0          5.96046e-8   0.0         -1.19209e-7   0.0          5.96046e-8   0.0
 -2.98023e-8   0.0          5.96046e-8   0.0          0.0          0.0          0.0          0.0          5.96046e-8  …   0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0
  0.0          0.0          0.0          0.0          0.0          5.96046e-8   0.0         -5.96046e-8   0.0             0.0         -2.98023e-8   0.0          0.0          0.0          0.0         -1.19209e-7  -5.96046e-8
  0.0          0.0          0.0          0.0          0.0          1.19209e-7   0.0         -1.19209e-7   1.19209e-7      5.96046e-8   0.0          0.0          0.0          5.96046e-8   0.0         -1.19209e-7   0.0
  0.0         -1.19209e-7   0.0         -5.96046e-8   0.0         -1.19209e-7   0.0          0.0         -5.96046e-8     -5.96046e-8   0.0          0.0          0.0          0.0         -1.19209e-7  -5.96046e-8   0.0
  0.0          0.0          0.0          0.0         -1.19209e-7   1.19209e-7   0.0          0.0          0.0             1.19209e-7  -1.19209e-7  -5.96046e-8   0.0          0.0          0.0          0.0          0.0
  0.0          0.0         -5.96046e-8  -2.98023e-8   5.96046e-8   5.96046e-8  -5.96046e-8  -5.96046e-8   1.49012e-8  …   0.0          0.0          0.0         -2.98023e-8   0.0         -1.19209e-7   0.0         -2.98023e-8
  0.0          0.0         -5.96046e-8  -2.98023e-8   0.0          0.0          0.0          2.98023e-8   0.0             0.0          0.0          0.0          5.96046e-8   0.0         -5.96046e-8   0.0          0.0
  0.0         -5.96046e-8  -1.19209e-7   0.0          0.0         -5.96046e-8  -5.96046e-8   0.0         -5.96046e-8      0.0          0.0          0.0          0.0         -2.98023e-8   0.0          5.96046e-8  -1.19209e-7
 -2.98023e-8   0.0          0.0          5.96046e-8  -1.19209e-7   0.0          5.96046e-8   5.96046e-8   0.0             1.19209e-7   0.0          1.19209e-7   0.0          0.0         -5.96046e-8   0.0         -1.19209e-7
 -5.96046e-8   0.0         -5.96046e-8   0.0          0.0         -5.96046e-8   0.0          0.0          0.0             5.96046e-8   0.0         -5.96046e-8   5.96046e-8   0.0          0.0          0.0         -1.19209e-7
  5.96046e-8   0.0          0.0          0.0          0.0          0.0          0.0          5.96046e-8   5.96046e-8  …   5.96046e-8   0.0          0.0         -5.96046e-8   5.96046e-8   0.0          0.0          0.0
  0.0          0.0          0.0         -1.19209e-7   0.0         -1.19209e-7   0.0          0.0          0.0             0.0          0.0          0.0          5.96046e-8  -5.96046e-8   0.0          0.0          0.0
  0.0          0.0          0.0          0.0          0.0          0.0          5.96046e-8   0.0          0.0             0.0          0.0          5.96046e-8   0.0          0.0          0.0          0.0          0.0
  0.0          0.0          5.96046e-8   5.96046e-8   0.0          5.96046e-8  -1.49012e-8  -2.98023e-8  -5.96046e-8      0.0          0.0          5.96046e-8   2.98023e-8   0.0          1.19209e-7   0.0          0.0
  0.0          0.0          5.96046e-8   0.0          0.0          0.0          5.96046e-8   0.0          1.19209e-7      0.0          5.96046e-8  -5.96046e-8   0.0          0.0          0.0          0.0          0.0
 -5.96046e-8   0.0          0.0          0.0         -2.98023e-8   0.0          0.0          0.0          0.0         …   0.0          0.0         -1.19209e-7   0.0          0.0          0.0          0.0          0.0
  0.0          0.0          5.96046e-8   5.96046e-8   0.0          0.0          0.0         -1.19209e-7   1.19209e-7     -1.19209e-7   0.0          0.0          0.0          0.0          0.0          0.0          0.0
  0.0          1.19209e-7  -5.96046e-8  -5.96046e-8  -2.98023e-8  -5.96046e-8   0.0          5.96046e-8   0.0             0.0         -5.96046e-8   0.0         -2.98023e-8   0.0         -5.96046e-8  -2.98023e-8   0.0
 -5.96046e-8   0.0          0.0         -5.96046e-8   5.96046e-8  -2.98023e-8   0.0          5.96046e-8   0.0             0.0          0.0         -1.19209e-7  -5.96046e-8   0.0          0.0          0.0          0.0
  0.0          5.96046e-8   0.0         -1.19209e-7   0.0         -1.49012e-8   0.0          0.0          5.96046e-8      2.98023e-8   5.96046e-8  -1.19209e-7  -1.19209e-7   5.96046e-8  -2.98023e-8   0.0         -5.96046e-8
  5.96046e-8  -5.96046e-8  -5.96046e-8   0.0          0.0          0.0          5.96046e-8   0.0          2.98023e-8  …   2.98023e-8   0.0          5.96046e-8   0.0          0.0         -5.96046e-8  -5.96046e-8  -5.96046e-8
  0.0          0.0          0.0         -5.96046e-8   0.0          0.0          0.0          0.0          0.0             0.0          0.0          2.98023e-8   0.0          0.0          0.0          0.0          5.96046e-8

julia> isapprox(CrossCor(w[end:-1:1, end:-1:1, :, :], [0.0])(x), Conv(w, [0.0])(x), rtol=1e-7)
true
```
So as shown, the fix is to change the test to a) change the eltype of `w`, and b) use `isapprox` with a higher tolerence like https://github.com/FluxML/Flux.jl/blob/master/test/layers/conv.jl#L121 does. Once that passes locally for you, feel free to update this PR or start a new one and we'll see what CI thinks about it.

**Comment by colbec** [comment]
OK thanks for this, it's a bit beyond my current level of contribution so I will withdraw this effort and get back to it when I can.

**Comment by ToucheSir** [comment]
No worries, thanks for the PR!

**Pull request closed without merging**
