### PR TITLE
Replace Juno with ProgressLogging

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
cc @pfitzseb @vchuravy 

@pfitzseb what would be the equivalent to replace the rendering from Juno?

### CODE REVIEW

**Comment by pfitzseb** [comment]
You could use https://github.com/pfitzseb/TreeViews.jl instead, but I'd recommend just deleting that code, tbh.

**Comment by DhairyaLGandhi** [comment]
That assumes the length of the dataset is known already iiuc. Iteration does not.

**Comment by darsnack** [comment]
True, but what would you log then? There are some issues about open ended logging on ProgressLogging.jl, but AFAIK the package only supports finite length logging.

**Comment by darsnack** [comment]
Maybe we don't call `@logprogress` for unknown or infinite length iterators?

**Comment by ToucheSir** [comment]
@DhairyaLGandhi this basically just needs a rebase, right?

**Comment by ToucheSir** [comment]
If you'd like, I can do the cleanup work for this.

**Comment by DhairyaLGandhi** [comment]
This would need a bit more work than a rebase. ProgressLogging isn't exactly compatible with Juno's, but as long as we have some fallbacks in place, we can merge this.

**Comment by ToucheSir** [comment]
The only API we're switching over is `Juno.@progress` to `ProgressLogging.@progress`. For the 2 places the former is used, the latter should have the same behaviour.

**Comment by DhairyaLGandhi** [comment]
superseded by #1807

**Comment by DhairyaLGandhi** [comment]
There's no guarantee for a known length to the `data` arg in `train!`. In some cases, the termination will happen only once some accuracy criteria is met and more samples would be generated indefinitely

**Pull request closed without merging**
