### PR TITLE
Added Iterator For Batches

### PR DESCRIPTION
**Pull request by shreyas-kowshik**
Addresses #317 
I am unable to understand exactly what needs to be done in case of epochs. Can someone please clarify?

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
We need to consider what all cases need to be handled when we create iterators.
- One major one being that of having labelled data (esp. if shuffling is involved).
- This function doesn't seem to create iterators, rather creates copies of the data, which is best avoided.
- We also need to take care of classic cases, with images etc.
- We currently don't return batches, rather just singular datapoints

I would expect something like this to work as
```julia
julia> x = rand(28,28,3, 100);

julia> it = batch_iter(x, 5);

# `it` is an iterator that returns a batch of 5 random images, picked from `x`

julia> first(it) # should be ((28,28,3,5),)
(28, 28, 3)
```

I also feel we should document examples of using `partition` clearly. Note that the way you've used it makes it such that we create chunks of `BATCH_ALL` size, instead of the batches we need.

Also might be worth checking out https://github.com/FluxML/Flux.jl/issues/150 if you haven't already. We need to make it such that we can ask for N epochs from calling the batches over as many times.

Thanks for the patch! :)

**Comment by shreyas-kowshik** [comment]
@dhairyagandhi96 Sorry for the late reply. I have changed the basic structure to address generic Arrays of images and feature data. An example of using the `batch_iter` is also added.
This approach now does not require copies of the original data. Rather it just needs to store a partition over the batch indices.

**Comment by dhairyagandhi96** [comment]
We should also have a nice way of demanding these batches for an entire epochs worth of training

**Comment by shreyas-kowshik** [comment]
@dhairyagandhi96 Added the options for training over multiple epochs. The feature to shuffle the batches is made optional.

**Comment by johnnychen94** [comment]
Please follow the [Iterator Interface](https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-iteration-1), also check https://github.com/JuliaLang/julia/blob/master/base/iterators.jl#L75-L103 for inspiration.

**Comment by datnamer** [comment]
There are some pretty cool data iterators here: https://mldatautilsjl.readthedocs.io/en/latest/data/pattern.html

**Pull request closed without merging**
