### PR TITLE
Layer normalisation for images

### LINKED ISSUE #406: Layer normalisation does not work for images
The layer uses the `normalise` (stateless) function as defined [here](https://github.com/FluxML/Flux.jl/blob/master/src/layers/stateless.jl#L42-L53). This function calculates mean and std on `dims=1` but for images we need `dims=(1,2,3)` leaving out only the batch dimension. The following function should work:
```julia
function normalise(x)
    d = ndims(x) == 4 ? [1,2,3] : [1,]
    mu = Flux.mean(x, dims=d)
    sd = Flux.std(x, dims=d, mean=mu)
    return (x.-mu)./sd
end
```
also the type of `x` has to change in the function signature to allow for images, currently `x::AbstractVecOrMat` fails for e.g. `rand(Float32, 84,84,1,1)` since it allows only 1d or 2d arrays.

### PR DESCRIPTION
**Pull request by MJ10**
Resolves #406 

As suggested by @MikeInnes and @skariel, added `dims` argument to function, with default value as 1 and changed type of `x` to `AbstractArray`

### CODE REVIEW

**Comment by MikeInnes** [comment]
LGTM. I think the docstring is a bit confusing. Maybe something like, "Normalises `x` to mean 0 and standard deviation 1, across the dimensions given by `dims`. Defaults to normalising over columns."

**Comment by MJ10** [comment]
That sounds better, I'll make the changes.

**Comment by dhairyagandhi96** [comment]
Oops, looks like GitHub's Web UI isn't happy about the conflict resolution. Can you take a look at the spurious changes please?

Many thanks!

**Comment by MJ10** [comment]
Sorry about the multiple pushes, made wrong commit by mistake.
I've resolved the conflicts now.

**Comment by MJ10** [comment]
Really sorry about that, fixed it.

**Comment by dhairyagandhi96** [comment]
Absolutely no worries. Thanks for the PR!

Could you add the keyword `corrected` as is there in master currently?
Looks good to me!

**Comment by MJ10** [comment]
I missed that while resolving the conflicts, sorry!

**Pull request merged**
