### PR TITLE
Add FashionMNIST

### PR DESCRIPTION
**Pull request by c-p-murphy**
Thought this might be a useful addition to the datasets that are included.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Cool! It looks like most of the code is shared with MNIST itself, so perhaps it'd be good to reuse some of the utilities there rather than duplicating?

**Comment by c-p-murphy** [comment]
Yeah, that definitely makes sense. I think it reuses everything that can be now, but if I missed anything just let me know.

**Comment by MikeInnes** [comment]
Perfect. Thanks a lot!

**Comment by c-p-murphy** [comment]
Awesome, happy to help.

**Pull request merged**
