### PR TITLE
Fix for 0.7 and 1.0 updates

### PR DESCRIPTION
**Pull request by JoshChristie**

### CODE REVIEW

**Comment by ayush1999** [comment]
I'm getting a `ERROR: LoadError: UndefVarError: A not defined` based on these changes. StackTrace:
```
ERROR: LoadError: UndefVarError: A not defined
Stacktrace:
 [1] show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Type{fatal: error thrown and no exception handler available.
UndefVarError(var=:A)
rec_backtrace at /buildworker/worker/package_linux64/build/src/stackwalk.c:94
record_backtrace at /buildworker/worker/package_linux64/build/src/task.c:246
jl_throw at /buildworker/worker/package_linux64/build/src/task.c:577
jl_undefined_var_error at /buildworker/worker/package_linux64/build/src/rtutils.c:134
show at /home/ayush99/.julia/dev/Flux/src/tracker/array.jl:34
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
show_datatype at ./show.jl:526
show at ./show.jl:436
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
print at ./strings/io.jl:31
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
print at ./strings/io.jl:42
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
show_tuple_as_call at ./show.jl:1490
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
show_spec_linfo at ./stacktraces.jl:261
#show#9 at ./stacktraces.jl:272
unknown function (ip: 0x7f78746ce083)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
#show at ./none:0 [inlined]
#show_trace_entry#631 at ./errorshow.jl:469
unknown function (ip: 0x7f78746cd94c)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
#show_trace_entry at ./none:0
unknown function (ip: 0x7f78746cd648)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
show_backtrace at ./errorshow.jl:572
#showerror#613 at ./errorshow.jl:79
unknown function (ip: 0x7f78746cacb7)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
#showerror at ./none:0
unknown function (ip: 0x7f78746ca932)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
#showerror#616 at ./errorshow.jl:85
unknown function (ip: 0x7f78746ca847)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
showerror at ./errorshow.jl:84 [inlined]
display_error at ./client.jl:99
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
display_error at ./client.jl:102
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1536 [inlined]
jl_f__apply at /buildworker/worker/package_linux64/build/src/builtins.c:556
jl_f__apply_latest at /buildworker/worker/package_linux64/build/src/builtins.c:594
#invokelatest#1 at ./essentials.jl:686 [inlined]
invokelatest at ./essentials.jl:685 [inlined]
_start at ./client.jl:423
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
jl_apply at /buildworker/worker/package_linux64/build/ui/../src/julia.h:1536 [inlined]
true_main at /buildworker/worker/package_linux64/build/ui/repl.c:112
main at /buildworker/worker/package_linux64/build/ui/repl.c:233
__libc_start_main at /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
_start at /home/ayush99/julia-1.0.0/bin/julia (unknown line)
```

**Comment by avik-pal** [comment]
I have pulled your fixes and made some additional fixes. Hope u don't mind

**Comment by JoshChristie** [comment]
Nice, I amended a commit which fixes that issue.

**Comment by avik-pal** [comment]
All the tests are passing, only we need to define the getindex. So u can pull the stuff in from my PR.

**Comment by ayush1999** [comment]
@JoshChristie I've pushed a small test fix to my branch : https://github.com/ayush1999/Flux.jl/tree/1.0 . Please pull changes.

**Comment by avik-pal** [comment]
Locally I get all tests passed. Adapt.jl PR needs to be merged first for tests to pass here.

**Comment by JoshChristie** [comment]
Nice work @avik-pal and @ayush1999, this PR has both your changes. 
 
I think supporting minimum 0.7 makes sense.

**Comment by ayush1999** [comment]
Tests pass locally but `Conv` doesn't work.
```
julia> Conv((3,3), 1=>2, relu)
ERROR: MethodError: no method matching ntuple(::getfield(Flux, Symbol("##67#68")){Int64}, ::Type{Val{2}})
Closest candidates are:
  ntuple(::F, ::Integer) where F at tuple.jl:133
  ntuple(::Any, ::Val{0}) at tuple.jl:155
  ntuple(::Any, ::Val{1}) at tuple.jl:156
  ...
Stacktrace:
 [1] expand(::Type, ::Int64) at /home/ayush99/.julia/dev/Flux/src/layers/conv.jl:6
 [2] _broadcast_getindex at ./broadcast.jl:574 [inlined]
 [3] (::getfield(Base.Broadcast, Symbol("##17#18")){Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple},Nothing,typeof(Flux.expand),Tuple{Base.RefValue{Type{Val{2}}},Tuple{Int64,Int64,Int64}}}})(::Int64) at ./broadcast.jl:922
 [4] ntuple at ./tuple.jl:158 [inlined]
 [5] tuplebroadcast at ./broadcast.jl:922 [inlined]
 [6] copy at ./broadcast.jl:920 [inlined]
 [7] materialize at ./broadcast.jl:724 [inlined]
 [8] #Conv#69(::Int64, ::Int64, ::Int64, ::Type, ::TrackedArray{…,Array{Float64,4}}, ::TrackedArray{…,Array{Float64,1}}, ::Function) at /home/ayush99/.julia/dev/Flux/src/layers/conv.jl:30
 [9] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:stride, :pad, :dilation),Tuple{Int64,Int64,Int64}}, ::Type{Conv}, ::TrackedArray{…,Array{Float64,4}}, ::TrackedArray{…,Array{Float64,1}}, ::Function) at ./none:0
 [10] #Conv#70(::Function, ::Int64, ::Int64, ::Int64, ::Type, ::Tuple{Int64,Int64}, ::Pair{Int64,Int64}, ::Function) at /home/ayush99/.julia/dev/Flux/src/layers/conv.jl:34
 [11] Conv(::Tuple{Int64,Int64}, ::Pair{Int64,Int64}, ::Function) at /home/ayush99/.julia/dev/Flux/src/layers/conv.jl:34
 [12] top-level scope at none:0
```

**Comment by ayush1999** [comment]
@JoshChristie Pushed final changes here: https://github.com/ayush1999/Flux.jl/tree/1.0 . Should solve the `Conv` error. Thanks!

**Comment by ayush1999** [comment]
@JoshChristie Can you start the travis build again? The corresponding changes in Adapt.jl  have been merged.

**Comment by MikeInnes** [comment]
Thanks all! :tada:

**Pull request merged**
