### PR TITLE
Batch dimensioning for single channel inputs

### PR DESCRIPTION
**Pull request by thebhatman**
Let's say you have a batch of thousand 32x32 single-channel images. Then x will be a three-dimensional array and weights will be a four-dimensional array. So, in this case, we need the size(x) to be 32x32x1x1000. This takes care of it.

### CODE REVIEW

**Comment by thebhatman** [comment]
Travis CI says "Failed to connect to storage.googleapis.com port 443: Connection timed out
gzip: stdin: unexpected end of file".

**Comment by dhairyagandhi96** [comment]
I've restarted the job, hopefully that was a spurious fail.

**Comment by thebhatman** [comment]
@dhairyagandhi96 , I am now trying to implement Batch dimensioning using dispatch(I am new to this). My last commit was using dispatch. Can you tell me if I am on the right track?

**Comment by MikeInnes** [comment]
You're being overly restrictive in the type parameters here; `Conv` needs to work on more than just 2D inputs and on number types other than Float64.

Also, this makes the channel dimension optional rather than the batch dimension.

**Comment by thebhatman** [comment]
Yes. I agree. I started off by trying to solve this small subproblem. Now I am working on the generalization of the conditions required.

**Comment by ToucheSir** [comment]
Given the lack of activity, need to generalize to higher dimensions (e.g. Flux3D) and existence of `Flux.unsqueeze`, I think this can be safely closed.

**Pull request closed without merging**
