### PR TITLE
Try using latest cu(DNN) binaries

### PR DESCRIPTION
**Pull request by ToucheSir**
Possible alternative to #1822.

### CODE REVIEW

**Comment by ToucheSir** [comment]
bors try

**Comment by DhairyaLGandhi** [comment]
Was there some background to this? Is there sometji g abou the cudnn we were using causing this?

**Review by DhairyaLGandhi — APPROVED** [review]
bors r+

**Comment by ToucheSir** [comment]
Testing whether this note from https://docs.nvidia.com/deeplearning/cudnn/release-notes/rel_8.html#rel-830 applies:
> In some cases, cudnnConvolutionBackwardFilter() generates numerically imprecise results when used with algo set to CUDNN_CONVOLUTION_BWD_FILTER_ALGO_1. This issue is most frequently encountered with three dimensional spatial tensors. Users of the backend API may explicitly avoid backend engine 2032 or consider the numerical notes of engines and reject any marked as offering reduced precision reduction (CUDNN_NUMERICAL_NOTE_REDUCED_PRECISION_REDUCTION).

**Pull request merged**
