### PR TITLE
Pull Request Template

### PR DESCRIPTION
**Pull request by MikeInnes**
Hopefully makes it a little clearer what the requirements are, which will lead to easier review, and encourage things like NEWS.md that we want to be better in sync.

cc @dhairyagandhi96 and @CarloLucibello for thoughts.

### CODE REVIEW

**Comment by CarloLucibello** [comment]
looks fine,  I like the conciseness compared to other templates you see around

**Comment by MikeInnes** [comment]
We could make it even more concise if we split into "bug fix" and "feature" templates. Not sure if that's worthwhile at this stage.

**Comment by dhairyagandhi96** [comment]
Seems good, easy checklist too

**Comment by MikeInnes** [comment]
Alright, let's run with it for now and we can tweak as we go along.

bors r+

**Pull request merged**
