### PR TITLE
remove some warnings in the test outputs

### PR DESCRIPTION
**Pull request by CarloLucibello**
and also some formatting changes

### CODE REVIEW

**Comment by CarloLucibello** [comment]
Only warnings left are of the type 
```julia
┌ Warning: Wrapping a custom walk function as an `AnonymousWalk`. Future versions will only support custom walks that explicitly subtyle `AbstractWalk`.
│   caller = fmap(f::Function, x::Chain{Tuple{Dense{typeof(identity), Matrix{Float32}, Bool}, Dense{typeof(identity), Matrix{Float32}, Bool}, Dense{typeof(identity), Matrix{Float32}, Bool}}}, ys::NamedTuple{(:layers,), Tuple{Tuple{NamedTuple{(:weight, :bias, :σ), Tuple{Int64, Tuple{}, Tuple{}}}, NamedTuple{(:weight, :bias, :σ), Tuple{Int64, Tuple{}, Tuple{}}}, NamedTuple{(:weight, :bias, :σ), Tuple{Int64, Tuple{}, Tuple{}}}}}}; exclude::Function, walk::Function, cache::IdDict{Any, Any}, prune::Functors.NoKeyword) at maps.jl:7
```
I still have to investigate where they come from

**Comment by CarloLucibello** [comment]
merge?

**Comment by mcabbott** [comment]
Either this or #2139 is going to be a fun rebase, sadly.

Are there any other PRs similarly affected? That (and git blame) are the objections to fixing white-space extensively, without other reasons for change.

**Comment by ToucheSir** [comment]
The issue with blame can be fixed via specifying ignored revs. Metalhead already [does this](https://github.com/FluxML/Metalhead.jl/blob/master/.git-blame-ignore-revs). It's also why it makes sense to batch formatting changes where possible and ensure future code remains formatted.

**Comment by CarloLucibello** [comment]
closing as outdated

**Pull request closed without merging**
