### PR TITLE
Add asymmetric padding

### PR DESCRIPTION
**Pull request by staticfloat**
This goes on top of https://github.com/FluxML/Flux.jl/pull/714, since NNlib now has support for asymmetrical padding this provides the Flux-level API for it.

### CODE REVIEW

**Comment by MikeInnes** [comment]
May as well fold into #714?

**Comment by staticfloat** [comment]
Sure, if you like, just close #714 and merge this one when https://github.com/FluxML/Tracker.jl/pull/11 is merged.

**Comment by staticfloat** [comment]
@MikeInnes looks like we're good to go, merge at your leisure.

**Comment by MikeInnes** [comment]
Thanks a lot @staticfloat.

I suspect it'd be cleaner to store the `Dims` object in the layer, rather than storing the same settings and reconstructing it on the fly. But that's not important for now.

**Comment by staticfloat** [comment]
> I suspect it'd be cleaner to store the Dims object in the layer, 

I thought of that, but considering that we need to re-create it for every differently-sized `x`, it wasn't high on my priority list.  It may save us a little bit of time, but not that much.  :P

**Comment by MikeInnes** [comment]
Ah yes, I didn't realise you're actually including the size of the input. This is probably the right way to do it then.

**Pull request merged**
