### PR TITLE
Add custom model example to docs.

### PR DESCRIPTION
**Pull request by Gregliest**
This PR adds a simple custom model example to the docs. As discussed in Slack, this example would have helped me understand how all the pieces fit together. But, happy to edit/move/delete as desired. 

cc @ToucheSir 

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [x] Documentation, if applicable
- [ ] API changes require approval from a committer (different from the author, if applicable)

### CODE REVIEW

**Comment by Gregliest** [comment]
Alright, I addressed all your comments. Looks like doctests are failing in basics.md, do you want me to have a look at that as well?

**Review by ToucheSir — DISMISSED** [review]
Sorry about the delay. If you're still interested, I think fixing basics.md in a separate PR would be great (to my knowledge, it should be a simple matter of formatting). This is good to go though.

**Review by ToucheSir — APPROVED** [review]

**Comment by logankilpatrick** [comment]
Can we bors this @ToucheSir ?

**Comment by DhairyaLGandhi** [comment]
I'm wondering if this makes sense as a tutorial in the model zoo. Showing not just the structure based model, but also one that doesn't involve any structure and is very functional. We already have a similar example in the vae model and the cppn etc, but I wonder if an even more basic one is warranted.

**Comment by ToucheSir** [comment]
@logankilpatrick Bors is failing to integrate because of failures on the `staging` branch and possibly `master`, see discussion in https://github.com/FluxML/Flux.jl/pull/1797.

**Pull request merged**
