### PR TITLE
Fix crossentropy when some probabilities are zero

### PR DESCRIPTION
**Pull request by cossio**
Use a function `xlogy(x,y) = x * log(y)` that has the correct limit at `x=0`.

Before this PR:

```julia
julia> Flux.crossentropy([0.1,0.0,0.9], [0.1,0.0,0.9])
NaN
```

After this PR:

```julia
julia> Flux.crossentropy([0.1,0.0,0.9], [0.1,0.0,0.9])
0.3250829733914482
```

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
Lgtm 

bors r+

**Comment by CarloLucibello** [comment]
Has this been tested on gpu with `allowscalar=False`? 
Crossentropy is quite ubiquitous and performance sensitive, I'm not sure we want to introduce that branching just to cover the zero case. How does this compare to adding an eps inside the log?

**Comment by cossio** [comment]
Note that `ifelse` should not branch. I have not tested, but I guess it should not make a difference.

**Comment by CarloLucibello** [comment]
Looks like it's not gpu friendly https://gitlab.com/JuliaGPU/Flux.jl/-/jobs/542058740

**Comment by dhairyagandhi96** [comment]
Interesting, I thought `ifelse` would be generic across devices.

**Comment by cossio** [comment]
`ifelse` is used here: https://github.com/JuliaGPU/CuArrays.jl/blob/master/src/nnlib.jl, for example.

**Comment by dhairyagandhi96** [comment]
Correct, I guess it's just the `cufunc` treatment

bors try

**Comment by cossio** [comment]
Looks ok now.

**Comment by cossio** [comment]
@dhairyagandhi96 Can you rerun bors? (I think I cannot do it myself, right?)

**Comment by cossio** [comment]
bors try

**Comment by dhairyagandhi96** [comment]
bors try

**Comment by cossio** [comment]
Merge? Also, would it be ok to register a patch version with this?

**Pull request merged**
