### PR TITLE
Ignore Zeros when gathering parameters

### LINKED ISSUE #1277: Flux.Zeros conflicts with Flux.loadparams!
Consider a model where all convolutions have their biases disabled:

```julia
m = Chain(
    Conv((3, 3), 1 => 2, bias=Flux.Zeros()),
    Conv((3, 3), 2 => 3, bias=Flux.Zeros()),
    Conv((3, 3), 3 => 4, bias=Flux.Zeros()),
)
```

If I collect its parameters (e.g. for saving them later) and print:

```julia
mp = m |> params .|> cpu
for p in mp
    println("$(typeof(p)) $(size(p))")
end
```

in the output I will have:

```
Array{Float32,4} (3, 3, 1, 2)
Array{Bool,0} () <--- disabled bias from 1st conv
Array{Float32,4} (3, 3, 2, 3)
Array{Float32,4} (3, 3, 3, 4)
```

So parameters of the model contain disabled bias, but only from the 1st layer (since parameters are stored in `Zygote.IdSet` others are ignored).
Moreover if I want to load these parameters into the model:

```julia
Flux.loadparams!(m, mp)
```

I get error `ERROR: setindex! not defined for Flux.Zeros{Bool,0}`.

Easy fix would be to define `params!` for `Flux.Zeros` that does not add it to parameters:

```julia
params!(p::Flux.Params, x::Flux.Zeros{<:Number}, seen = Flux.IdSet()) = nothing
```

I wanted to create a PR with this fix, but this solution conflicts with [this test](https://github.com/FluxML/Flux.jl/blob/master/test/layers/conv.jl#L49) which expects `Flux.Zeros` to be in parameters.
Maybe change it to instead check that `bias` is not in gradients?

### PR DESCRIPTION
**Pull request by pxl-th**
This fixes #1277.
IMO, it makes more sense to ignore disabled parameters when gathering model parameters, than have something that is not used and may lead to confusion.

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable
- [ ] Final review from `@dhairyagandhi96` (for API changes).

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Removing Zeros from the list params might give incorrect results for loading complete chains where it is expected to see the bias term appear.

**Comment by pxl-th** [comment]
In this case there is an issue, if we have a model with all biases disabled:

```julia
m = Chain(
    Conv((3, 3), 1=>2, bias=Flux.Zeros()),
    Conv((3, 3), 2=>3, bias=Flux.Zeros()),
    Conv((3, 3), 3=>4, bias=Flux.Zeros()),
)
```

Then in parameters we have `Flux.Zeros` only from first convolution, since parameters are stored in `Zygote.Params` which wraps `IdSet{Any}` and so we effectively loose information about all other disabled biases.

```julia
for p in Flux.params(m)
    println(typeof(p))
end

>>> Output:
Array{Float32,4}
Flux.Zeros{Bool,0}
Array{Float32,4}
Array{Float32,4}
```

**Comment by DhairyaLGandhi** [comment]
The crucial thing to note here is that we check for the presence of `Flux.Zeros` in the model side. That way the information is preserved. To make them different, we could make the struct mutable to create new instances of it with every call.

**Comment by pxl-th** [comment]
Closing as it is not relevant anymore

**Pull request closed without merging**
