### PR TITLE
fix typo in models overview document

### PR DESCRIPTION
**Pull request by teamclouday**
I saw this when I was viewing the introductory [tutorial](https://fluxml.ai/Flux.jl/stable/models/overview/).  
So I want to help fix it.  

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [x] Documentation, if applicable
- [ ] API changes require approval from a committer (different from the author, if applicable)

### CODE REVIEW

**Review by darsnack — APPROVED** [review]
Thanks for this!

**Comment by darsnack** [comment]
Failures on nightly appear unrelated. Thanks again!

bors r+

**Comment by darsnack** [comment]
Fixes #1609

**Review by DhairyaLGandhi — APPROVED** [review]
bors r+

**Pull request merged**
