### PR TITLE
Add Maxpool and Meanpool for convention.

### PR DESCRIPTION
**Pull request by yuehhua**

### CODE REVIEW

**Comment by MikeInnes** [comment]
Looks good, thanks! A couple comments:

I think `MaxPool` and `MeanPool` would look better.

It'd be nice if I could provide the keyword arguments as scalars and have them expanded to tuples (as with convolutions now).

Could you also add some simple tests (doesn't have to do much more than checking it can be constructed and called).

**Comment by yuehhua** [comment]
Done! Is it good?

**Comment by yuehhua** [comment]
@MikeInnes ?

**Comment by MikeInnes** [comment]
Thanks @yuehhua! I tweaked things a little to be closer to what I had in mind earlier (but didn't explain well).

**Pull request merged**
