### PR TITLE
Add `TrackedArray` support for `repeat(x; inner, outer)`

### PR DESCRIPTION
**Pull request by staticfloat**
This makes it really easy to do things like make `Upsample` layers, which are pretty useful for autoencoders.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Yeah I just meant using existing GPU-friendly primitives; you can sometimes hack broadcasting to do stuff like this (e.g. kronecker products) but it sounds like that's not really the case here. I'm sure we can figure out the kernel later anyway.

**Comment by staticfloat** [comment]
I suppose you could write a massively parallel version where you construct a source index from every destination index, then run `A[dest_idxs] .= B[src_idxs]`.

**Comment by MikeInnes** [comment]
@americast might be worth looking at what this needs to work on the GPU.

@staticfloat thanks for the patch!

**Comment by americast** [comment]
Sure, will have a look :+1:

**Pull request merged**
