### PR TITLE
Workaround for BatchNorm Float64 grad with Float32 input

### PR DESCRIPTION
**Pull request by aterenin**
This works around #757.

The cause is as follows: BatchNorm gradients get promoted to Float64 is due to element-wise integer division. I don't know why Tracker is doing that - I could look into it but don't understand Tracker internals particularly well. Simply performing floating point division instead of integer division eliminates the issue.

### CODE REVIEW

**Comment by KristofferC** [comment]
See https://github.com/FluxML/Flux.jl/pull/538 for another way of working around the same issue.

**Comment by aterenin** [comment]
Is there any reason to prefer one fix to the other? I can modify my PR if your fix is preferable.

**Comment by MikeInnes** [comment]
Either seems fine to me. It would be nice to have a test though.

**Comment by aterenin** [comment]
It seems this issue got lost in my email inbox half a year ago. Sorry about that.

I'm not sure what kind of test to write for it. Any suggestions?

**Comment by aterenin** [comment]
Oops, accidentally pressed the wrong button and closed this. My apologies.

**Pull request closed without merging**
