### PR TITLE
Fixes #900

### LINKED ISSUE #900: ConvTranspose gradient error: no method matching iterate(::Nothing)
This code fails with `ERROR: MethodError: no method matching iterate(::Nothing)`
```julia
using Flux

m = ConvTranspose((3,3), 2=>1)
x = rand(10,10,2,1)

gradient(()->sum(m(x)), params(m))
```

Here's the full stacktrace:
```
julia> gradient(()->sum(m(x)), params(m))
ERROR: MethodError: no method matching iterate(::Nothing)
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:568
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:568
  iterate(::ExponentialBackOff) at error.jl:199
  ...
Stacktrace:
 [1] _zip_iterate_some at .\iterators.jl:350 [inlined]
 [2] _zip_iterate_all at .\iterators.jl:342 [inlined]
 [3] iterate at .\iterators.jl:332 [inlined]
 [4] iterate at .\generator.jl:44 [inlined]
 [5] collect(::Base.Generator{Base.Iterators.Zip{Tuple{Array{typeof(∂(λ)),1},Nothing}},getfield(Base, Symbol("##3#4")){getfield(Zygote, Symbol("##945#949"))}}) at .\array.jl:606
 [6] map(::Function, ::Array{typeof(∂(λ)),1}, ::Nothing) at .\abstractarray.jl:2091
 [7] (::getfield(Zygote, Symbol("##944#948")){Array{typeof(∂(λ)),1}})(::Nothing) at C:\Users\jules\.julia\packages\Zygote\lRotY\src\lib\array.jl:121
 [8] (::getfield(Zygote, Symbol("##952#953")){getfield(Zygote, Symbol("##944#948")){Array{typeof(∂(λ)),1}}})(::Nothing) at C:\Users\jules\.julia\packages\Zygote\lRotY\src\lib\array.jl:136
 [9] getindex at .\tuple.jl:26 [inlined]
 [10] (::typeof(∂(getindex)))(::Nothing) at C:\Users\jules\.julia\packages\Zygote\lRotY\src\compiler\interface2.jl:0
 [11] (::typeof(∂(Flux.conv_transpose_dims)))(::Nothing) at C:\Users\jules\.julia\packages\Flux\WxpHb\src\layers\conv.jl:109
 [12] (::typeof(∂(λ)))(::FillArrays.Fill{Float64,4,NTuple{4,Base.OneTo{Int64}}}) at C:\Users\jules\.julia\packages\Flux\WxpHb\src\layers\conv.jl:124
 [13] #27 at .\none:1 [inlined]
 [14] (::typeof(∂(getfield(Main, Symbol("##27#28"))())))(::Float64) at C:\Users\jules\.julia\packages\Zygote\lRotY\src\compiler\interface2.jl:0
 [15] (::getfield(Zygote, Symbol("##38#39")){Zygote.Params,Zygote.Context,typeof(∂(getfield(Main, Symbol("##27#28"))()))})(::Float64) at C:\Users\jules\.julia\packages\Zygote\lRotY\src\compiler\interface.jl:101
 [16] gradient(::Function, ::Zygote.Params) at C:\Users\jules\.julia\packages\Zygote\lRotY\src\compiler\interface.jl:47
 [17] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by dhairyagandhi96**
Thoughts on the test?

cc @MikeInnes

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
Ref #900

**Comment by MikeInnes** [comment]
Can you add a TODO to the `@nograd` linking to the issue? Just so we know it's a short-term fix that could be removed eventually.

**Comment by dhairyagandhi96** [comment]
Done

**Pull request merged**
