### PR TITLE
Fixes #1354

### LINKED ISSUE #1354: Broken methods(Base.show)
https://github.com/FluxML/Flux.jl/blob/master/src/data/tree.jl#L17
`Base.show(io::IO, t::Type{Tree{T}}) where T = print(io, "Tree{", T, "}")`
has broken printing, the method can't be printed.

### PR DESCRIPTION
**Pull request by racinmat**
### PR Checklist

- [x] Tests are added
- [-] Entry in NEWS.md
- [-] Documentation, if applicable
- [-] Final review from `@dhairyagandhi96` (for API changes).

Fixes #1354 
added tests that `Base.show(methods(Base.show))` in same manner as in https://github.com/FluxML/Zygote.jl/pull/809.

Could this PR be labeled by hacktoberfest-accepted?
Thanks.

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Thanks, bors r+

**Comment by CarloLucibello** [comment]
> Thanks, bors r+

bors command needs to be on a separate line, AFAIK

bors r+

**Comment by racinmat** [comment]
Damn, tests are failing because fix for https://github.com/FluxML/Zygote.jl/issues/808 is not released yet. 
Should I modify the testcase to test only the flux methods?

**Comment by racinmat** [comment]
fixed test, testing only methods defined in Flux

**Pull request merged**
