### PR TITLE
Add RADAM optimizer

### LINKED ISSUE #841: RAdam Optimizer
There's a new optimizer out there that's supposed to be good:

https://medium.com/@lessw/new-state-of-the-art-ai-optimizer-rectified-adam-radam-5d854730807b

### PR DESCRIPTION
**Pull request by baggepinnen**
Closes #841

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
Good to add it in the tests

Also, thanks for the optimiser!

**Comment by jamesjscully** [comment]
There's also an export in the Optimize.jl file

**Comment by jamesjscully** [comment]
Also did you try the optimizer? i coded this myself tonight and came up with essentially the same code. I tried my code and yours. Both were giving some strange results

**Comment by baggepinnen** [comment]
Yeah, it trains but is quite unstable..

**Comment by MikeInnes** [comment]
Looks like the tests are failing.

**Comment by dhairyagandhi96** [comment]
As @jamesjscully pointed; needs an export from Optimise.jl

**Comment by baggepinnen** [comment]
Should be fixed now (Y)

**Comment by dhairyagandhi96** [comment]
Can we also add a news item, please?

Thanks!

**Comment by baggepinnen** [comment]
News entry added

**Comment by MikeInnes** [comment]
Bors failure appears to be unrelated. Thanks @baggepinnen!

**Pull request merged**
