### PR TITLE
Stop type treason with show of the TrackedArray type

### LINKED ISSUE #434: Showing array of param's  crashes julia
```
using Flux
using Flux.Tracker

D, N = (4, 10_000)
H = 100

W1 = param(rand(H, D))
b1 = param(rand(H))
W2 = param(rand(1, H))
b2 = param(rand(1))

θ = [W1, b1, W2, b2]
# ^This errors and crashes julia

4-element Array{Error showing value of type Array{ERROR: UndefVarError: A not defined
Stacktrace:
 [1] show(::IOContext{REPL.Terminals.TTYTerminal}, ::Type{SYSTEM: show(lasterr) caused an error
UndefVarError(:A)
```

### PR DESCRIPTION
**Pull request by iamed2**
Fixes https://github.com/FluxML/Flux.jl/issues/468
Fixes #434

### CODE REVIEW

**Comment by MikeInnes** [comment]
What's the type treason – is there actually something incorrect about this method or is it just a Base bug?

**Comment by iamed2** [comment]
You can see [Jeff's comment](https://github.com/JuliaLang/julia/issues/24195#issuecomment-337744534) for my previous encounter on a different package.

Basically this function is used for some critical display features (like showing method tables) which must not error. The specific crash I encountered was showing `TrackedArray{S, N, Array{S, N}} where {N, S<:Real}`, which is demonstrated in #468. I believe it has to do with showing unbound TypeVars.

**Comment by MikeInnes** [comment]
Seems fair in the case there's a bug on our side, but it also seems like this method should never be called with `A` unbound. Doesn't happen in these cases, for example:
```
julia> foo(::Array{Complex{T}}) where T = 1
foo (generic function with 1 method)

julia> foo([1+2im])
1

julia> foo(Complex[1+2im])
ERROR: MethodError: no method matching foo(::Array{Complex,1})
Closest candidates are:
  foo(::Array{Complex{T},N} where N) where T at REPL[1]:1
Stacktrace:
 [1] top-level scope at none:0

julia> foo(::Type{Complex{T}}) where T = 1
foo (generic function with 2 methods)

julia> foo(Complex)
ERROR: MethodError: no method matching foo(::Type{Complex})
Closest candidates are:
  foo(::Array{Complex{T},N} where N) where T at REPL[1]:1
  foo(::Type{Complex{T}}) where T at REPL[4]:1
```

Maybe I'm misunderstanding some way in which those are different.

Perhaps we can work around this by checking `@isdefined A`?

**Comment by MikeInnes** [comment]
What I mean is, AFAICT the method we define here is not actually applicable to `TrackedArray{Int}`, so it's not clear to me why it's being called at all.

**Comment by iamed2** [comment]
It actually happens during display of `TrackedArray{Int}`, when it's displayng `TrackedArray{Int}.body`

**Comment by ararslan** [comment]
Can this be merged? It's a fairly unobtrusive change and it fixes a rather nasty error.

**Comment by AlexRobson** [comment]
I think it'll also fix https://github.com/FluxML/Flux.jl/issues/434

**Comment by MikeInnes** [comment]
Ok looks like it can be reproduced with
```julia
julia> foo(::Type{Complex{T}}) where T = T
foo (generic function with 1 method)

julia> Complex.body
Complex{T<:Real}

julia> foo(Complex.body)
ERROR: UndefVarError: T not defined
```
This is just a really strange case, I guess. Let's try the fixed method and we can revisit it if further problems come up. Thanks a lot for narrowing this down @iamed2!

**Pull request merged**
