### PR TITLE
Reshape with Tuple Dimensions and Kronecker Product 

### LINKED ISSUE #149: Kronecker Product on Tracked Arrays No Method Matching *
Trying to do a Kronecker Product of two tracked arrays and have a no method matching for `*`:
```
kron(param(eye(2)),param(eye(2)))
#=> MethodError: no method matching *(::TrackedArray{…,Array{Float64,0}}, ::TrackedArray{…,Array{Float64,0}})
```

### PR DESCRIPTION
**Pull request by jessebett**
Fixes #149 
(though not in the more clever `∂(X⊗Y) = (∂X)⊗Y + X⊗(∂Y)` we also discussed.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Awesome, thanks! Can you add a quick gradient test to this? Should be easy following [these](https://github.com/FluxML/Flux.jl/blob/master/test/tracker.jl).

**Comment by jessebett** [comment]
So I added some tests which made me aware of some confusing things (which I guess is the point of writing tests...)

First, I realized that my implementation of `kron` doesn't take Vector arguments, where `Base.kron` does, because it tries to access the second dimension. I guess this is what you meant by the `∂(X⊗Y) = (∂X)⊗Y + X⊗(∂Y)` implementation being more clever by not caring about dimensions.

However, after I realized this I was confused because `@test gradtest(kron,rand(5), rand(3))` passed? This can't be my `kron` method though, so how is this passing?

Further, this only passes sometimes, every tenth or so time I run the test it doesn't pass. 
What's concerning is this is true for all the tests. I was running them repeatedly and most of the time they were passing, but randomly they'd fail. 

Obviously this is now a different issue I'm describing. I think my kron implementation passes, it fails as infrequently as the others. Though I don't know why the `kron` on `Vector` arguments is working. Is mine now unnecessary?

**Comment by MikeInnes** [comment]
Julia defines [these methods for vectors], so we get that for free :)

I didn't realise that Julia only defines this for matrices anyway, in which case it's not a big deal if we only support matrices.

**Comment by MikeInnes** [comment]
I've updated this slightly; we shouldn't overwrite the base method, but only use our version when TrackedArrays are involved.

Otherwise, this is perfect, thanks a lot @jessebett!

**Comment by jessebett** [comment]
Okay! I now see how to avoid overwriting base, cool!

At some point later I might try to implement `∂(X⊗Y) = (∂X)⊗Y + X⊗(∂Y)` but I think it'll require a bit more understanding of how Flux writes the `back` rules.

Thanks @MikeInnes!
(this was my first ever PR)

**Comment by MikeInnes** [comment]
Awesome, great first PR!

BTW, looking at it again I'm not sure if that rule will help us here; you'd have to effectively solve for `dX` given `dY` and `d(XxY)` which requires a definition of the inverse of Kronecker product. That said, I'm not sure it even matters as the clever broadcast version looks pretty efficient to me. (and also looks like it would generalise to N-dimensions if anyone's up for a challenge).

I'm planning to write up some docs on the AD stuff though.

**Pull request merged**
