### PR TITLE
RNN failure hackaround

### PR DESCRIPTION
**Pull request by MikeInnes**
See #923.

bors try

### CODE REVIEW

**Comment by MikeInnes** [comment]
Although bors went through, the CI pipeline has failed; I'm guessing that means this didn't fix the issue for real.

bors try

**Comment by dhairyagandhi96** [comment]
Seems #923 related still

**Comment by MikeInnes** [comment]
Now using Tim's hackaround in https://github.com/JuliaGPU/CuArrays.jl/pull/517.

bors try

**Comment by MikeInnes** [comment]
Test runner seems to be having trouble. Trying again.

bors r+

**Comment by maleadt** [comment]
One runner's GPU died:

```
$ nvidia-smi                                                                                                                                                                                                                
Unable to determine the device handle for GPU 0000:41:00.0: Unknown Error
```

**Comment by maleadt** [comment]
Looks good! I'll restart the job to try and flush out errors.

**Comment by MikeInnes** [comment]
So is CI up again?

bors try

**Comment by maleadt** [comment]
> bors r+

just FYI, that'll embed a reference to `tb/workspace` in the Flux Manifest. That branch will disappear as soon as https://github.com/JuliaGPU/CuArrays.jl/pull/517 is merged. So it might be better to wait until it's part of `master` and use that hash?

**Comment by MikeInnes** [comment]
Yeah, if the branch is going to be deleted immediately then that's best to avoid.

bors r-

**Comment by maleadt** [comment]
As soon as CI is green on CuArrays I'll merge so that we can move on here.

**Pull request merged**
